---
extends: default

ignore: |
  helm/*/templates/
  deploy/helmfile.yaml
  reports/

rules:
  document-start: disable
  indentation:
    indent-sequences: consistent
  line-length:
    max: 160
    level: warning
  truthy:
    allowed-values: ["true", "false", "on", "off"]
