---
- name: Include OS-specific package tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
  when: ansible_os_family in ['Debian', 'RedHat', 'FreeBSD']

- name: Disable swap on Linux
  ansible.builtin.command: swapoff -a
  when: ansible_system == 'Linux'
  changed_when: false

- name: Configure Kubernetes sysctl values
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  loop:
    - {name: 'net.ipv4.ip_forward', value: '1'}
    - {name: 'net.bridge.bridge-nf-call-iptables', value: '1'}
  when: ansible_system == 'Linux'
