default: nginx
defaultIngressClass: traefik
providers:
  nginx:
    image: nginxinc/nginx-unprivileged:1.30.0
    ports:
    - 80
    ingressClass: traefik
    status: default
  apache-httpd:
    image: httpd:2.4
    ports:
    - 80
    - 443
    ingressClass: apache
    status: supported
  apache-tomcat:
    image: tomcat:10.1
    ports:
    - 8080
    ingressClass: tomcat
    status: supported
  traefik:
    image: traefik:v3.1
    ports:
    - 80
    - 443
    - 8080
    ingressClass: traefik
    status: supported
