version: '3.9'
name: urban-platform-infra
x-defaults:
  restart: unless-stopped
  networks:
  - urban-platform
services:
  app-01:
    image: ${REGISTRY_PREFIX:-}example-app-01:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5013:5013
    - 5021:5021
  app-02:
    image: ${REGISTRY_PREFIX:-}example-app-02:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5006:5006
  app-03:
    image: ${REGISTRY_PREFIX:-}example-app-03:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5019:5019
    - 3000:3000
  app-04:
    image: ${REGISTRY_PREFIX:-}example-app-04:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5020:5020
    - 3001:3001
  app-05:
    image: ${REGISTRY_PREFIX:-}example-app-05:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5004:5004
  app-06:
    image: ${REGISTRY_PREFIX:-}example-app-06:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5023:5023
  app-07:
    image: ${REGISTRY_PREFIX:-}example-app-07:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5036:5036
  app-08:
    image: ${REGISTRY_PREFIX:-}example-app-08:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5037:5037
  app-09:
    image: ${REGISTRY_PREFIX:-}example-app-09:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5009:5009
  app-10:
    image: ${REGISTRY_PREFIX:-}example-app-10:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5032:5032
  app-11:
    image: ${REGISTRY_PREFIX:-}example-app-11:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5040:5040
  app-12:
    image: ${REGISTRY_PREFIX:-}example-app-12:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5031:5031
  app-13:
    image: ${REGISTRY_PREFIX:-}example-app-13:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5010:5010
  app-14:
    image: ${REGISTRY_PREFIX:-}example-app-14:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5024:5024
  app-15:
    image: ${REGISTRY_PREFIX:-}example-app-15:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 4000-4199:4000-4199
  app-16:
    image: ${REGISTRY_PREFIX:-}example-app-16:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5021:5021
  app-17:
    image: ${REGISTRY_PREFIX:-}example-app-17:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5035:5035
  app-18:
    image: ${REGISTRY_PREFIX:-}example-app-18:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5005:5005
  app-19:
    image: ${REGISTRY_PREFIX:-}example-app-19:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5001:5001
  app-20:
    image: ${REGISTRY_PREFIX:-}example-app-20:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5029:5029
  app-21:
    image: ${REGISTRY_PREFIX:-}example-app-21:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5030:5030
  app-22:
    image: ${REGISTRY_PREFIX:-}example-app-22:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5025:5025
  app-23:
    image: ${REGISTRY_PREFIX:-}example-app-23:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5027:5027
  app-24:
    image: ${REGISTRY_PREFIX:-}example-app-24:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5034:5034
  app-25:
    image: ${REGISTRY_PREFIX:-}example-app-25:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5008:5008
  app-26:
    image: ${REGISTRY_PREFIX:-}example-app-26:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5028:5028
  app-27:
    image: ${REGISTRY_PREFIX:-}example-app-27:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5000:5000
  app-28:
    image: ${REGISTRY_PREFIX:-}example-app-28:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5011:5011
  app-29:
    image: ${REGISTRY_PREFIX:-}example-app-29:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5007:5007
  app-30:
    image: ${REGISTRY_PREFIX:-}example-app-30:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5038:5038
  app-31:
    image: ${REGISTRY_PREFIX:-}example-app-31:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5026:5026
  app-32:
    image: ${REGISTRY_PREFIX:-}example-app-32:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5022:5022
  app-33:
    image: ${REGISTRY_PREFIX:-}example-app-33:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5002:5002
  app-34:
    image: ${REGISTRY_PREFIX:-}example-app-34:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5003:5003
  app-35:
    image: ${REGISTRY_PREFIX:-}example-app-35:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5033:5033
  app-36:
    image: ${REGISTRY_PREFIX:-}example-app-36:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5017:5017
  app-37:
    image: ${REGISTRY_PREFIX:-}example-app-37:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5015:5015
  app-38:
    image: ${REGISTRY_PREFIX:-}example-app-38:0.1.0
    restart: unless-stopped
    networks:
    - urban-platform
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 3
    ports:
    - 5018:5018
  nginx:
    image: nginxinc/nginx-unprivileged:1.31.0
    restart: unless-stopped
    ports:
    - 80:8080
    networks:
    - urban-platform
    deploy:
      replicas: 3
  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.6
    restart: unless-stopped
    environment:
    - ZOOKEEPER_CLIENT_PORT=2181
    - ZOOKEEPER_TICK_TIME=2000
    networks:
    - urban-platform
    deploy:
      replicas: 1
  kafka:
    image: confluentinc/cp-kafka:7.9.6
    restart: unless-stopped
    depends_on:
    - zookeeper
    ports:
    - 29092:29092
    - 29094:29094
    environment:
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_BROKER_ID=1
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092
    - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
    - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    networks:
    - urban-platform
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    restart: unless-stopped
    ports:
    - 8080:8080
    environment:
    - KAFKA_CLUSTERS_0_NAME=urban-platform
    - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
    - kafka
    networks:
    - urban-platform
  redis:
    image: redis:8.6.2
    restart: unless-stopped
    ports:
    - 6379:6379
    networks:
    - urban-platform
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.4.1
    restart: unless-stopped
    ports:
    - 9200:9200
    - 9300:9300
    environment:
    - discovery.type=single-node
    - xpack.security.enabled=false
    volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
    - urban-platform
  kibana:
    image: docker.elastic.co/kibana/kibana:9.4.1
    restart: unless-stopped
    ports:
    - 5601:5601
    depends_on:
    - elasticsearch
    environment:
    - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
    - urban-platform
  logstash:
    image: docker.elastic.co/logstash/logstash:9.4.0
    restart: unless-stopped
    ports:
    - 5044:5044
    networks:
    - urban-platform
  zabbix-agent2:
    image: zabbix/zabbix-agent2:ubuntu-7.4.10
    restart: unless-stopped
    ports:
    - 10050:10050
    networks:
    - urban-platform
  db-01-postgres:
    image: postgres:18.3
    restart: unless-stopped
    ports:
    - 5451:5432
    environment:
    - POSTGRES_DB=app_db_01
    - POSTGRES_USER=app_db_01
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-change-me}
    volumes:
    - db-01-postgres-data:/var/lib/postgresql
    networks:
    - urban-platform
  db-02-postgres:
    image: postgres:18.3
    restart: unless-stopped
    ports:
    - 5452:5432
    environment:
    - POSTGRES_DB=app_db_02
    - POSTGRES_USER=app_db_02
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-change-me}
    volumes:
    - db-02-postgres-data:/var/lib/postgresql
    networks:
    - urban-platform
  db-03-postgres:
    image: postgres:18.3
    restart: unless-stopped
    ports:
    - 5439:5432
    environment:
    - POSTGRES_DB=app_db_03
    - POSTGRES_USER=app_db_03
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-change-me}
    volumes:
    - db-03-postgres-data:/var/lib/postgresql
    networks:
    - urban-platform
  db-04-postgres:
    image: postgres:18.3
    restart: unless-stopped
    ports:
    - 5433:5432
    environment:
    - POSTGRES_DB=app_db_04
    - POSTGRES_USER=app_db_04
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-change-me}
    volumes:
    - db-04-postgres-data:/var/lib/postgresql
    networks:
    - urban-platform
  db-05-postgres:
    image: postgres:18.3
    restart: unless-stopped
    ports:
    - 5450:5432
    environment:
    - POSTGRES_DB=app_db_05
    - POSTGRES_USER=app_db_05
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-change-me}
    volumes:
    - db-05-postgres-data:/var/lib/postgresql
    networks:
    - urban-platform
  db-06-postgres:
    image: postgres:18.3
    restart: unless-stopped
    ports:
    - 5435:5432
    environment:
    - POSTGRES_DB=app_db_06
    - POSTGRES_USER=app_db_06
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-change-me}
    volumes:
    - db-06-postgres-data:/var/lib/postgresql
    networks:
    - urban-platform
  db-07-postgres:
    image: postgres:18.3
    restart: unless-stopped
    ports:
    - 5446:5432
    environment:
    - POSTGRES_DB=app_db_07
    - POSTGRES_USER=app_db_07
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-change-me}
    volumes:
    - db-07-postgres-data:/var/lib/postgresql
    networks:
    - urban-platform
  db-08-postgres:
    image: postgres:18.3
    restart: unless-stopped
    ports:
    - 5432:5432
    environment:
    - POSTGRES_DB=app_db_08
    - POSTGRES_USER=app_db_08
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-change-me}
    volumes:
    - db-08-postgres-data:/var/lib/postgresql
    networks:
    - urban-platform
  db-09-postgres:
    image: postgres:18.3
    restart: unless-stopped
    ports:
    - 5434:5432
    environment:
    - POSTGRES_DB=app_db_09
    - POSTGRES_USER=app_db_09
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-change-me}
    volumes:
    - db-09-postgres-data:/var/lib/postgresql
    networks:
    - urban-platform
  db-10-postgres:
    image: postgres:18.3
    restart: unless-stopped
    ports:
    - 5441:5432
    environment:
    - POSTGRES_DB=app_db_10
    - POSTGRES_USER=app_db_10
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-change-me}
    volumes:
    - db-10-postgres-data:/var/lib/postgresql
    networks:
    - urban-platform
  db-11-postgres:
    image: postgres:18.3
    restart: unless-stopped
    ports:
    - 5437:5432
    environment:
    - POSTGRES_DB=app_db_11
    - POSTGRES_USER=app_db_11
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-change-me}
    volumes:
    - db-11-postgres-data:/var/lib/postgresql
    networks:
    - urban-platform
  db-12-postgres:
    image: postgres:18.3
    restart: unless-stopped
    ports:
    - 5449:5432
    environment:
    - POSTGRES_DB=app_db_12
    - POSTGRES_USER=app_db_12
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-change-me}
    volumes:
    - db-12-postgres-data:/var/lib/postgresql
    networks:
    - urban-platform
  db-13-postgres:
    image: postgres:18.3
    restart: unless-stopped
    ports:
    - 5444:5432
    environment:
    - POSTGRES_DB=app_db_13
    - POSTGRES_USER=app_db_13
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-change-me}
    volumes:
    - db-13-postgres-data:/var/lib/postgresql
    networks:
    - urban-platform
  db-14-postgres:
    image: postgres:18.3
    restart: unless-stopped
    ports:
    - 5436:5432
    environment:
    - POSTGRES_DB=app_db_14
    - POSTGRES_USER=app_db_14
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-change-me}
    volumes:
    - db-14-postgres-data:/var/lib/postgresql
    networks:
    - urban-platform
  db-15-postgres:
    image: postgres:18.3
    restart: unless-stopped
    ports:
    - 5440:5432
    environment:
    - POSTGRES_DB=app_db_15
    - POSTGRES_USER=app_db_15
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-change-me}
    volumes:
    - db-15-postgres-data:/var/lib/postgresql
    networks:
    - urban-platform
  db-16-postgres:
    image: postgres:18.3
    restart: unless-stopped
    ports:
    - 5443:5432
    environment:
    - POSTGRES_DB=app_db_16
    - POSTGRES_USER=app_db_16
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-change-me}
    volumes:
    - db-16-postgres-data:/var/lib/postgresql
    networks:
    - urban-platform
  db-17-postgis:
    image: postgis/postgis:18-3.6
    restart: unless-stopped
    ports:
    - 5438:5432
    environment:
    - POSTGRES_DB=app_db_17
    - POSTGRES_USER=app_db_17
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-change-me}
    volumes:
    - db-17-postgis-data:/var/lib/postgresql
    networks:
    - urban-platform
  timescaledb:
    image: timescale/timescaledb:2.26.4-pg18
    restart: unless-stopped
    ports:
    - 5448:5432
    environment:
    - POSTGRES_DB=timeseries
    - POSTGRES_USER=timeseries
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-change-me}
    volumes:
    - timescaledb-data:/var/lib/postgresql
    networks:
    - urban-platform
networks:
  urban-platform:
    driver: bridge
volumes:
  elasticsearch-data: {}
  db-01-postgres-data: {}
  db-02-postgres-data: {}
  db-03-postgres-data: {}
  db-04-postgres-data: {}
  db-05-postgres-data: {}
  db-06-postgres-data: {}
  db-07-postgres-data: {}
  db-08-postgres-data: {}
  db-09-postgres-data: {}
  db-10-postgres-data: {}
  db-11-postgres-data: {}
  db-12-postgres-data: {}
  db-13-postgres-data: {}
  db-14-postgres-data: {}
  db-15-postgres-data: {}
  db-16-postgres-data: {}
  db-17-postgis-data: {}
  timescaledb-data: {}
