#!/usr/bin/env python3
"""Generate and execute guarded Compose-to-platform migration automation."""
from __future__ import annotations

import argparse
import base64
import hashlib
import ipaddress
import json
import os
import re
import shlex
import shutil
import stat
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from typing import Any
from urllib.parse import quote

try:
    import yaml
except ModuleNotFoundError:  # pragma: no cover - exercised by operator setup.
    yaml = None

import import_project


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_VALUES = ROOT / "helm/urban-platform-infra/values.yaml"
DEFAULT_PRIVATE_DIR = Path("/var/lib/urban-platform/private")
SECRET_ENV_RE = import_project.SECRET_KEY_RE
GENERATED_HEADER = "# Generated by scripts/migrate_project.py. Keep private outputs out of Git.\n"
KUBERNETES_NAMESPACE_RETRIES = 6
KUBERNETES_NAMESPACE_RETRY_DELAY_SECONDS = 5


def require_yaml() -> None:
    if yaml is None:
        raise SystemExit("PyYAML is required. Install it with `python3 -m pip install PyYAML`.")


def k8s_name(value: str, prefix: str = "") -> str:
    safe = re.sub(r"[^a-z0-9-]+", "-", value.lower()).strip("-")
    safe = re.sub(r"-+", "-", safe) or "item"
    digest = hashlib.sha256(value.encode("utf-8")).hexdigest()[:8]
    base = f"{prefix}-{safe}" if prefix else safe
    base = base[:52].strip("-")
    return f"{base}-{digest}"[:63].strip("-")


def relative_compose_file(project_path: Path, file_name: str) -> Path:
    return project_path / file_name


def load_context(args: argparse.Namespace) -> tuple[Path, list[Path], list[tuple[import_project.ServiceRecord, dict[str, Any]]], list[import_project.Finding], dict[str, Any]]:
    require_yaml()
    project_path = Path(args.project_path).expanduser().resolve()
    if not project_path.exists() or not project_path.is_dir():
        raise SystemExit(f"Project path does not exist or is not a directory: {project_path}")

    values_path = Path(args.values).expanduser()
    if not values_path.is_absolute():
        values_path = (ROOT / values_path).resolve()
    policy_path = Path(args.image_policy).expanduser()
    if not policy_path.is_absolute():
        policy_path = (ROOT / policy_path).resolve()

    values = import_project.load_yaml(values_path)
    approved_images = import_project.normalize_approved_images(policy_path)
    selected_ingress = args.ingress_controller or values.get("ingress", {}).get("className", "traefik")
    selected_webserver = args.webserver or values.get("webserver", {}).get("provider", "nginx")
    selected_database = args.database or values.get("databases", {}).get("provider", "cloudnative-pg")
    expected_web_image = import_project.expected_webserver_image(values, selected_webserver)

    findings: list[import_project.Finding] = []
    compose_files = import_project.find_compose_files(project_path)
    service_pairs = import_project.read_compose_services(project_path, compose_files, findings)
    for record, service in service_pairs:
        import_project.analyze_service(
            service=service,
            record=record,
            findings=findings,
            approved_images=approved_images,
            selected_ingress=str(selected_ingress),
            selected_webserver=str(selected_webserver),
            selected_database=str(selected_database),
            expected_web_image=expected_web_image,
        )
    return project_path, compose_files, service_pairs, findings, values


def secret_entries(service: dict[str, Any]) -> dict[str, str]:
    entries: dict[str, str] = {}
    for key, value in import_project.environment_entries(service.get("environment")):
        if not SECRET_ENV_RE.search(key):
            continue
        if value is None or import_project.VARIABLE_VALUE_RE.match(value):
            continue
        entries[key] = value
    return entries


def service_has_docker_socket(service: dict[str, Any]) -> bool:
    for volume in service.get("volumes") or []:
        if isinstance(volume, dict):
            source = str(volume.get("source", ""))
            target = str(volume.get("target", ""))
            if "/var/run/docker.sock" in source or "/var/run/docker.sock" in target:
                return True
            continue
        if "/var/run/docker.sock" in str(volume):
            return True
    return False


def postgres_env(service: dict[str, Any]) -> dict[str, str]:
    env = {key: value for key, value in import_project.environment_entries(service.get("environment")) if value is not None}
    return {
        "user": env.get("POSTGRES_USER", "postgres"),
        "password": env.get("POSTGRES_PASSWORD", ""),
        "database": env.get("POSTGRES_DB", env.get("POSTGRES_USER", "postgres")),
    }


def published_port(record: import_project.ServiceRecord, target: str = "5432") -> str | None:
    for port in record.ports:
        if port.target == target and port.published:
            return port.published
    return None


def read_database_targets(path: str | None) -> dict[str, Any]:
    if not path:
        return {}
    target_path = Path(path).expanduser()
    if not target_path.exists():
        raise SystemExit(f"Database target map does not exist: {target_path}")
    data = yaml.safe_load(target_path.read_text(encoding="utf-8")) or {}
    targets = data.get("databaseTargets", data)
    if not isinstance(targets, dict):
        raise SystemExit("Database target map must be a mapping or contain `databaseTargets`.")
    return {str(key): value for key, value in targets.items()}


def kubectl_command(args: argparse.Namespace, command: list[str]) -> list[str]:
    base = ["kubectl"]
    if args.kubeconfig:
        base.extend(["--kubeconfig", args.kubeconfig])
    return [*base, *command]


def require_kubernetes_api(args: argparse.Namespace) -> None:
    if not args.execute:
        return
    command = kubectl_command(args, ["get", "--raw=/readyz", "--request-timeout=10s"])
    result = subprocess.run(command, text=True, capture_output=True)
    if result.returncode == 0:
        ensure_kubernetes_namespace(args)
        return
    details = "\n".join(part for part in [result.stdout.strip(), result.stderr.strip()] if part)
    kubeconfig_note = f" with kubeconfig {args.kubeconfig}" if args.kubeconfig else ""
    raise SystemExit(
        "Kubernetes API is not reachable"
        f"{kubeconfig_note}. import-auto cannot apply secrets, read target database secrets, or apply manifests until this is fixed.\n"
        "The Makefile now runs `make operator-kubeconfig` before import-auto; if this still fails, verify the RKE2 API/VIP listener, firewall rules, and cluster health.\n"
        f"kubectl output:\n{details}"
    )


def ensure_kubernetes_namespace(args: argparse.Namespace) -> None:
    get_command = kubectl_command(args, ["get", "namespace", args.namespace, "--request-timeout=15s"])
    create_command = kubectl_command(args, ["create", "namespace", args.namespace, "--request-timeout=30s"])

    last_details = ""
    for attempt in range(1, KUBERNETES_NAMESPACE_RETRIES + 1):
        result = subprocess.run(get_command, text=True, capture_output=True)
        if result.returncode == 0:
            return
        last_details = "\n".join(part for part in [result.stdout.strip(), result.stderr.strip()] if part)
        if "notfound" in last_details.replace(" ", "").lower() or "not found" in last_details.lower():
            break
        if attempt == KUBERNETES_NAMESPACE_RETRIES:
            raise SystemExit(
                f"Could not verify Kubernetes namespace `{args.namespace}` after {KUBERNETES_NAMESPACE_RETRIES} attempts.\n"
                "The Kubernetes API answered version checks, but namespace reads are timing out or failing.\n"
                f"kubectl output:\n{last_details}"
            )
        print(
            f"Kubernetes namespace check failed on attempt {attempt}/{KUBERNETES_NAMESPACE_RETRIES}; "
            f"retrying in {KUBERNETES_NAMESPACE_RETRY_DELAY_SECONDS}s."
        )
        time.sleep(KUBERNETES_NAMESPACE_RETRY_DELAY_SECONDS)

    for attempt in range(1, KUBERNETES_NAMESPACE_RETRIES + 1):
        run_display = " ".join(create_command)
        print(f"+ {run_display}")
        result = subprocess.run(create_command, text=True, capture_output=True)
        if result.returncode == 0:
            print(result.stdout, end="")
            return

        last_details = "\n".join(part for part in [result.stdout.strip(), result.stderr.strip()] if part)
        if "alreadyexists" in last_details.replace(" ", "").lower() or "already exists" in last_details.lower():
            return

        verify = subprocess.run(get_command, text=True, capture_output=True)
        if verify.returncode == 0:
            print(f"Kubernetes namespace `{args.namespace}` exists after create retry.")
            return

        if attempt == KUBERNETES_NAMESPACE_RETRIES:
            raise SystemExit(
                f"Could not create Kubernetes namespace `{args.namespace}` after {KUBERNETES_NAMESPACE_RETRIES} attempts.\n"
                "The cluster may be unhealthy or the API endpoint may be too slow for writes.\n"
                f"kubectl output:\n{last_details}"
            )
        print(
            f"Kubernetes namespace create failed on attempt {attempt}/{KUBERNETES_NAMESPACE_RETRIES}; "
            f"retrying in {KUBERNETES_NAMESPACE_RETRY_DELAY_SECONDS}s."
        )
        time.sleep(KUBERNETES_NAMESPACE_RETRY_DELAY_SECONDS)


def k8s_secret_data(namespace: str, name: str, kubeconfig: str = "") -> dict[str, str]:
    command = ["kubectl"]
    if kubeconfig:
        command.extend(["--kubeconfig", kubeconfig])
    command.extend(["-n", namespace, "get", "secret", name, "-o", "json"])
    result = subprocess.run(
        command,
        text=True,
        capture_output=True,
        check=True,
    )
    payload = json.loads(result.stdout)
    encoded_data = payload.get("data", {})
    return {
        key: base64.b64decode(value).decode("utf-8")
        for key, value in encoded_data.items()
    }


def target_dsn_from_mapping(target: Any, namespace: str, kubeconfig: str = "") -> str | None:
    if isinstance(target, str):
        if any(marker in target for marker in ["<target_", "<namespace>"]):
            return None
        return target
    if not isinstance(target, dict):
        return None

    host = target.get("host")
    database = target.get("database")
    port = target.get("port", 5432)
    username = target.get("username")
    password = target.get("password")
    secret_ref = target.get("secretRef") or target.get("secret")
    if isinstance(secret_ref, dict) and (not username or not password):
        secret_namespace = str(secret_ref.get("namespace") or namespace)
        secret_name = str(secret_ref.get("name"))
        try:
            secret_data = k8s_secret_data(secret_namespace, secret_name, kubeconfig)
        except subprocess.CalledProcessError:
            print(f"Could not read target database secret {secret_namespace}/{secret_name}; restore for this target will be skipped.")
            return None
        username = secret_data.get(str(secret_ref.get("usernameKey", "username")))
        password = password or secret_data.get(str(secret_ref.get("passwordKey", "password")))
        database = database or secret_data.get(str(secret_ref.get("databaseKey", "dbname")))
        host = host or secret_data.get(str(secret_ref.get("hostKey", "host")))
        port = target.get("port") or secret_data.get(str(secret_ref.get("portKey", "port")), 5432)
    if not host or not database or not username or not password:
        return None
    if str(password).startswith("<") or str(username).startswith("<") or str(database).startswith("<"):
        return None
    return f"postgresql://{quote(str(username), safe='')}:{quote(str(password), safe='')}@{host}:{port}/{quote(str(database), safe='')}"


def run_command(command: list[str], *, env: dict[str, str] | None = None, stdin: str | None = None, cwd: Path | None = None) -> None:
    display = " ".join(command)
    print(f"+ {display}")
    subprocess.run(command, input=stdin, text=True, env=env, cwd=str(cwd) if cwd else None, check=True)


def become_password(args: argparse.Namespace) -> str:
    password_file = getattr(args, "become_password_file", "")
    if password_file:
        path = Path(password_file).expanduser()
        try:
            lines = path.read_text(encoding="utf-8").splitlines()
        except OSError as exc:
            raise SystemExit(f"Could not read MIGRATION_BECOME_PASSWORD_FILE `{path}`: {exc}") from exc
        return lines[0] if lines else ""
    return os.environ.get("MIGRATION_BECOME_PASSWORD", "")


def run_remote_sudo_shell(args: argparse.Namespace, ssh_options: list[str], target: str, script: str) -> None:
    password = become_password(args)
    sudo_command = "sudo -S -p '' sh -lc" if password else "sudo -n sh -lc"
    run_command(
        ["ssh", *ssh_options, target, f"{sudo_command} {shlex.quote(script)}"],
        stdin=f"{password}\n" if password else None,
    )


def run_cleanup_command(command: list[str]) -> None:
    display = " ".join(command)
    print(f"+ {display}")
    result = subprocess.run(command)
    if result.returncode != 0:
        print(f"Cleanup command failed with exit code {result.returncode}; continuing.")


def write_file(path: Path, content: str, executable: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    if executable:
        path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP)


def secure_directory(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)
    try:
        path.chmod(0o700)
    except PermissionError:
        print(f"Could not chmod {path}; verify permissions manually.")


def secure_file(path: Path) -> None:
    try:
        path.chmod(0o600)
    except PermissionError:
        print(f"Could not chmod {path}; verify permissions manually.")


def registry_host(registry: str) -> str:
    return registry.split("/", 1)[0]


def container_tool(args: argparse.Namespace) -> str:
    cached = getattr(args, "_container_tool", "")
    if cached:
        return str(cached)

    requested = args.container_tool
    if requested != "auto":
        if shutil.which(requested):
            setattr(args, "_container_tool", requested)
            return requested
        raise SystemExit(
            f"Container tool `{requested}` was requested but is not installed on the operator machine.\n"
            "Install it, set MIGRATION_CONTAINER_TOOL to an available tool, or use MIGRATION_IMAGE_MODE=skip."
        )

    for candidate in ("docker", "podman"):
        if shutil.which(candidate):
            setattr(args, "_container_tool", candidate)
            return candidate

    raise SystemExit(
        "Image migration requires a local container CLI on the operator machine, but neither `docker` nor `podman` was found.\n"
        "Install Docker or Podman on urban-ops-01, then rerun import-auto. On RedHat-family hosts, Podman is usually enough: `sudo dnf install -y podman`.\n"
        "If you want to continue without building/preloading application images, rerun with MIGRATION_IMAGE_MODE=skip."
    )


def container_command(args: argparse.Namespace, *parts: str) -> list[str]:
    return [container_tool(args), *parts]


def ensure_registry_login(args: argparse.Namespace) -> None:
    if not args.execute or args.image_mode != "registry" or not args.registry:
        return
    username = os.environ.get("MIGRATION_REGISTRY_USERNAME")
    password = os.environ.get("MIGRATION_REGISTRY_PASSWORD")
    if not username or not password:
        print(f"Registry credentials were not provided in MIGRATION_REGISTRY_USERNAME/MIGRATION_REGISTRY_PASSWORD; using existing {container_tool(args)} login state.")
        return
    run_command(container_command(args, "login", registry_host(args.registry), "--username", username, "--password-stdin"), stdin=password)


def image_artifact_name(record: import_project.ServiceRecord) -> str:
    file_digest = hashlib.sha256(record.file.encode("utf-8")).hexdigest()[:8]
    return k8s_name(f"{record.name}-{file_digest}")


def image_archive_name(record: import_project.ServiceRecord) -> str:
    return f"{image_artifact_name(record)}.tar"


def local_import_image(args: argparse.Namespace, record: import_project.ServiceRecord) -> str:
    if args.registry:
        return f"{args.registry.rstrip('/')}/{image_artifact_name(record)}:{args.image_tag}"
    return f"urban-platform-import/{image_artifact_name(record)}:{args.image_tag}"


def container_image_exists(args: argparse.Namespace, image: str) -> bool:
    return subprocess.run(container_command(args, "image", "inspect", image), stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL).returncode == 0


def explicit_pull_reference(image: import_project.ImageRef) -> str:
    if image.variable:
        return image.display
    first_segment = image.repository.split("/", 1)[0]
    has_registry = "." in first_segment or ":" in first_segment or first_segment == "localhost"
    if has_registry:
        return image.display
    repository = image.repository
    if "/" not in repository:
        repository = f"docker.io/library/{repository}"
    else:
        repository = f"docker.io/{repository}"
    if image.digest:
        return f"{repository}@{image.digest}"
    if image.tag:
        return f"{repository}:{image.tag}"
    return repository


def pullable_image(image: import_project.ImageRef) -> bool:
    if image.variable:
        return False
    first_segment = image.repository.split("/", 1)[0]
    return "/" in image.repository or "." in first_segment or ":" in first_segment


def ensure_source_image(args: argparse.Namespace, record: import_project.ServiceRecord) -> tuple[bool, list[str]]:
    if record.image is None:
        return False, []
    source = record.image.display
    if container_image_exists(args, source):
        return True, []
    if pullable_image(record.image):
        pull_source = explicit_pull_reference(record.image)
        if pull_source != source and container_image_exists(args, pull_source):
            run_command(container_command(args, "tag", pull_source, source))
            return True, [source]
        print(f"Source image {source} is not local; pulling {pull_source} before import.")
        pull = subprocess.run(container_command(args, "pull", pull_source))
        if pull.returncode != 0:
            return False, []
        cleanup_images = [pull_source]
        if pull_source != source:
            run_command(container_command(args, "tag", pull_source, source))
            cleanup_images.append(source)
        return True, cleanup_images
    print(f"Source image {source} is not local and does not look pullable; skipping {record.name}.")
    return False, []


def cleanup_operator_container_tags(args: argparse.Namespace, images: list[str]) -> None:
    for image in sorted(set(images)):
        if container_image_exists(args, image):
            run_cleanup_command(container_command(args, "image", "rm", image))


def cleanup_operator_archives(archive_dir: Path) -> None:
    removed = 0
    for archive in sorted(archive_dir.glob("*.tar")):
        try:
            archive.unlink()
            removed += 1
        except OSError as exc:
            print(f"Could not remove local image archive {archive}: {exc}")
    if removed:
        print(f"Removed {removed} local preload archive(s) from {archive_dir}.")


def resolve_build_source(compose_path: Path, build: Any) -> tuple[Path, str, str | None]:
    if isinstance(build, dict):
        context_value = str(build.get("context", "."))
        dockerfile = str(build.get("dockerfile", "Dockerfile"))
    else:
        context_value = str(build)
        dockerfile = "Dockerfile"

    context = (compose_path.parent / context_value).resolve()
    fallback_note = None
    if not context.exists() and context_value not in {"", "."}:
        fallback_context = compose_path.parent.resolve()
        fallback_dockerfile = (fallback_context / dockerfile).resolve()
        if fallback_context.exists() and fallback_dockerfile.exists():
            fallback_note = f"Build context {context} does not exist; falling back to Compose file directory {fallback_context}."
            context = fallback_context

    return context, dockerfile, fallback_note


def preload_archives_to_nodes(args: argparse.Namespace, archive_dir: Path) -> bool:
    nodes = [node.strip() for node in args.rke2_nodes.split(",") if node.strip()]
    archives = sorted(archive_dir.glob("*.tar"))
    if not archives:
        print(f"No image archives were written to {archive_dir}.")
        return False
    if not nodes:
        print(f"Image archives written to {archive_dir}. Set MIGRATION_RKE2_NODES to copy them to RKE2 nodes automatically.")
        return False
    ssh_target_prefix = f"{args.ssh_user}@"
    ssh_options: list[str] = []
    if args.ssh_key:
        ssh_options.extend(["-i", args.ssh_key])
    remote_tmp = "/tmp/urban-platform-import-images"
    remote_image_dir = shlex.quote(args.rke2_image_dir)
    for node in nodes:
        target = node if "@" in node else f"{ssh_target_prefix}{node}"
        run_command(["ssh", *ssh_options, target, f"mkdir -p {remote_tmp}"])
        for archive in archives:
            run_command(["scp", *ssh_options, str(archive), f"{target}:{remote_tmp}/"])
        run_remote_sudo_shell(
            args,
            ssh_options,
            target,
            f"mkdir -p {shlex.quote(args.rke2_image_dir)} && cp {shlex.quote(remote_tmp)}/*.tar {shlex.quote(args.rke2_image_dir)}/",
        )
        archive_checks = " ".join(shlex.quote(f"{args.rke2_image_dir}/{archive.name}") for archive in archives)
        run_remote_sudo_shell(args, ssh_options, target, f"for archive in {archive_checks}; do test -s \"$archive\"; done")
        if args.rke2_import_images:
            import_preloaded_archives_to_containerd(args, ssh_options, target, remote_image_dir)
    return True


def import_preloaded_archives_to_containerd(args: argparse.Namespace, ssh_options: list[str], target: str, remote_image_dir: str) -> None:
    script = (
        "set -e; "
        "ctr=/var/lib/rancher/rke2/bin/ctr; "
        "socket=/run/k3s/containerd/containerd.sock; "
        f"image_dir={remote_image_dir}; "
        "if [ -S \"$socket\" ] && [ -x \"$ctr\" ]; then "
        "for archive in \"$image_dir\"/*.tar; do "
        "[ -e \"$archive\" ] || continue; "
        "\"$ctr\" --address \"$socket\" -n k8s.io images import \"$archive\"; "
        "done; "
        "\"$ctr\" --address \"$socket\" -n k8s.io images ls >/dev/null; "
        "echo \"Imported preload archives into running RKE2 containerd.\"; "
        "else "
        "echo \"RKE2 containerd is not running on this node; archives are present for startup import.\"; "
        "fi"
    )
    run_remote_sudo_shell(args, ssh_options, target, script)


def database_instances(values: dict[str, Any], namespace: str) -> list[dict[str, Any]]:
    instances = values.get("databases", {}).get("instances", {})
    targets: list[dict[str, Any]] = []
    for name, config in instances.items():
        if not isinstance(config, dict) or not config.get("enabled", False):
            continue
        engine = str(config.get("engine", "postgresql"))
        database = str(config.get("database", name))
        owner = str(config.get("owner", database))
        targets.append(
            {
                "name": str(name),
                "engine": engine,
                "host": f"{name}-rw.{namespace}.svc",
                "port": int(config.get("postgresPort", 5432)),
                "database": database,
                "owner": owner,
                "secretRef": {
                    "name": f"{name}-app",
                    "namespace": namespace,
                    "usernameKey": "username",
                    "passwordKey": "password",
                },
            }
        )
    return targets


def target_for_record(record: import_project.ServiceRecord, available: list[dict[str, Any]], index: int) -> dict[str, Any]:
    matching_index = next((i for i, target in enumerate(available) if target["engine"] == record.kind), None)
    if matching_index is None and record.kind == "postgresql":
        matching_index = next((i for i, target in enumerate(available) if target["engine"] in {"postgres", "postgresql"}), None)
    if matching_index is None and available:
        matching_index = 0
    if matching_index is None:
        return {
            "host": f"{k8s_name(record.name)}-rw.<namespace>.svc",
            "port": 5432,
            "database": "<target_database>",
            "username": "<target_user>",
            "password": "<target_password>",
        }
    return available.pop(matching_index)


def generated_database_targets(
    service_pairs: list[tuple[import_project.ServiceRecord, dict[str, Any]]],
    values: dict[str, Any],
    namespace: str,
) -> dict[str, Any]:
    available = database_instances(values, namespace)
    mapping: dict[str, Any] = {}
    database_records = [
        record
        for record, _service in service_pairs
        if record.kind in {"postgresql", "postgis", "timescaledb"}
    ]
    for index, record in enumerate(database_records):
        target = target_for_record(record, available, index)
        entry = {
            "sourceAlias": k8s_name(record.name),
            "targetService": target.get("name", "<target-service>"),
            "host": target["host"],
            "port": target["port"],
            "database": target["database"],
        }
        if target.get("secretRef"):
            entry["secretRef"] = target["secretRef"]
        if target.get("username"):
            entry["username"] = target["username"]
        if target.get("password"):
            entry["password"] = target["password"]
        mapping[record.name] = entry
    return {"databaseTargets": mapping}


def write_database_target_map(path: Path, service_pairs: list[tuple[import_project.ServiceRecord, dict[str, Any]]], values: dict[str, Any], namespace: str) -> None:
    should_replace_placeholder = False
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        should_replace_placeholder = "service-name-or-alias" in existing
    if path.exists() and not should_replace_placeholder:
        secure_file(path)
        print(f"Database target map already exists: {path}")
        return
    write_file(path, yaml.safe_dump(generated_database_targets(service_pairs, values, namespace), sort_keys=False))
    secure_file(path)
    print(f"Database target map initialized: {path}")


def render_private_report(
    args: argparse.Namespace,
    private_report: Path,
    project_path: Path,
    compose_files: list[Path],
    service_pairs: list[tuple[import_project.ServiceRecord, dict[str, Any]]],
    findings: list[import_project.Finding],
    values: dict[str, Any],
) -> None:
    report = import_project.render_report(
        project_path=project_path,
        compose_files=compose_files,
        service_records=[record for record, _service in service_pairs],
        findings=findings,
        selected_ingress=args.ingress_controller,
        selected_webserver=args.webserver,
        selected_database=args.database,
        expected_web_image=import_project.expected_webserver_image(values, args.webserver),
        database_targets=import_project.database_target_images(values),
        redact_sensitive=False,
    )
    write_file(private_report, report)
    secure_file(private_report)
    print(f"Private import report written: {private_report}")


def handled_error_reason(args: argparse.Namespace, finding: import_project.Finding) -> str | None:
    if finding.severity != "ERROR":
        return None
    if args.allow_secret_material and "literal secret value" in finding.message:
        return "automated-secret-import"
    if args.skip_docker_socket_services and "/var/run/docker.sock" in finding.message:
        return "skipped-docker-socket-service"
    return None


def write_operator_action_plan(args: argparse.Namespace, findings: list[import_project.Finding]) -> None:
    private_dir = Path(args.private_dir).expanduser()
    action_plan = private_dir / "operator-action-plan.md"
    error_findings = [finding for finding in findings if finding.severity == "ERROR"]
    handled = [(finding, handled_error_reason(args, finding)) for finding in error_findings]
    handled = [(finding, reason) for finding, reason in handled if reason]
    unhandled = [finding for finding in error_findings if handled_error_reason(args, finding) is None]

    lines = [
        "# Import Operator Action Plan",
        "",
        "This file is generated automatically by `scripts/migrate_project.py` and contains exact private Compose paths and service names.",
        "",
        f"- Automated/accepted hard blockers: `{len(handled)}`",
        f"- Manual hard blockers: `{len(unhandled)}`",
        f"- Literal secret import enabled: `{str(args.allow_secret_material).lower()}`",
        f"- Docker socket services skipped: `{str(args.skip_docker_socket_services).lower()}`",
        "",
        "## Automated Or Accepted",
        "",
    ]
    if handled:
        for finding, reason in handled:
            lines.append(
                f"- `{reason}` `{finding.file}` :: `{finding.service}` - {finding.message}"
            )
    else:
        lines.append("- None.")

    lines.extend(["", "## Manual Blockers", ""])
    if unhandled:
        for finding in unhandled:
            lines.append(
                f"- `{finding.file}` :: `{finding.service}` - {finding.message} Recommendation: {finding.recommendation}"
            )
    else:
        lines.append("- None. The migration can continue with the selected automation flags.")

    lines.extend(
        [
            "",
            "## Notes",
            "",
            "- Literal secrets are imported into Kubernetes Secrets only when `MIGRATION_ALLOW_SECRET_MATERIAL=true` is set.",
            "- Services that mount `/var/run/docker.sock` are not carried into Kubernetes as Docker-socket integrations.",
            "- The source Compose files are not rewritten by this automation.",
            "",
        ]
    )
    write_file(action_plan, "\n".join(lines))
    secure_file(action_plan)
    print(f"Operator action plan written: {action_plan}")


def fail_on_unhandled_errors(args: argparse.Namespace, findings: list[import_project.Finding]) -> None:
    unhandled = [
        finding
        for finding in findings
        if finding.severity == "ERROR" and handled_error_reason(args, finding) is None
    ]
    if not unhandled:
        return
    print("Import automation stopped because manual blockers remain:")
    for finding in unhandled:
        print(f"- {finding.file}::{finding.service} - {finding.message}")
    print(f"Private report: {Path(args.private_dir).expanduser() / 'import-check-private.md'}")
    print(f"Operator action plan: {Path(args.private_dir).expanduser() / 'operator-action-plan.md'}")
    raise SystemExit(f"Import automation stopped with {len(unhandled)} manual blocker(s).")


def print_bundle_files(output: Path) -> None:
    if not output.exists():
        return
    print("Migration bundle files:")
    for path in sorted(item for item in output.rglob("*") if item.is_file()):
        print(f"- {path.relative_to(output)}")


def stage_prepare(
    args: argparse.Namespace,
    project_path: Path,
    compose_files: list[Path],
    service_pairs: list[tuple[import_project.ServiceRecord, dict[str, Any]]],
    findings: list[import_project.Finding],
    values: dict[str, Any],
) -> None:
    private_dir = Path(args.private_dir).expanduser()
    secure_directory(private_dir)
    secure_directory(Path(args.dump_dir).expanduser())
    db_targets_path = Path(args.db_targets).expanduser() if args.db_targets else private_dir / "db-targets.yaml"
    write_database_target_map(db_targets_path, service_pairs, values, args.namespace)
    render_private_report(
        args=args,
        private_report=private_dir / "import-check-private.md",
        project_path=project_path,
        compose_files=compose_files,
        service_pairs=service_pairs,
        findings=findings,
        values=values,
    )
    write_operator_action_plan(args, findings)
    ensure_registry_login(args)


def generate_bundle(
    args: argparse.Namespace,
    project_path: Path,
    service_pairs: list[tuple[import_project.ServiceRecord, dict[str, Any]]],
    findings: list[import_project.Finding],
    values: dict[str, Any],
) -> None:
    output = Path(args.output).expanduser()
    output.mkdir(parents=True, exist_ok=True)
    redactor = import_project.ReportRedactor(args.redact_sensitive)
    service_records = [record for record, _service in service_pairs]
    database_targets = import_project.database_target_images(values)
    expected_web_image = import_project.expected_webserver_image(values, args.webserver)

    plan_lines = [
        "# Import Migration Automation",
        "",
        f"- Project path: `{redactor.project_path(project_path)}`",
        f"- Namespace: `{args.namespace}`",
        f"- Private registry: `{args.registry or 'not configured'}`",
        f"- Image tag: `{args.image_tag}`",
        f"- Private operator directory: `{args.private_dir}`",
        f"- Dump directory: `{args.dump_dir}`",
        f"- Database target map: `{args.db_targets or str(Path(args.private_dir).expanduser() / 'db-targets.yaml')}`",
        f"- Image mode: `{args.image_mode}`",
        f"- Auto prepare: `{str(args.auto_prepare).lower()}`",
        f"- Execute mode: `{str(args.execute).lower()}`",
        f"- Redacted output: `{str(args.redact_sensitive).lower()}`",
        "",
        "## Automation Entry Points",
        "",
        "- `run-migration.sh` runs all guarded stages.",
        "- Automatic preparation creates the private report, DB target map, dump directory, and optional registry login before guarded stages run.",
        "- `scripts/01-sync-secrets.sh` applies Kubernetes Secrets from Compose secret environment values when explicitly allowed.",
        "- `scripts/02-build-and-push-images.sh` builds application images. Use image mode `registry` to push, `preload` to export/copy tar archives to RKE2 nodes, or `skip` for external Compose transition mode.",
        "- `scripts/03-database-dump-restore.sh` dumps PostgreSQL-family sources and restores only targets defined in the private database target map.",
        "- `scripts/04-generate-routing-and-storage.sh` writes Traefik, ConfigMap, Secret, and PVC candidate manifests.",
        "- `scripts/05-validate.sh` re-runs the compatibility checker.",
        "",
        "## Guardrails",
        "",
        "- Dry-run is the default. Use `MIGRATION_EXECUTE=true` only on the trusted operator machine.",
        "- Secret and database stages require `MIGRATION_ALLOW_SECRET_MATERIAL=true` so secret values are read only at execution time.",
        "- Database restore uses the private `MIGRATION_DB_TARGETS` file. The generated map targets CloudNativePG app secrets when platform database instances exist.",
        "- Registry login is used only with image mode `registry`. Image mode `preload` avoids registry login by writing image archives and optionally copying them to RKE2 nodes.",
        "- Generated output must stay in `reports/` or another ignored/private directory.",
        "",
    ]
    import_project.render_migration_plan(
        lines=plan_lines,
        service_records=service_records,
        findings=findings,
        redactor=redactor,
        selected_ingress=args.ingress_controller,
        selected_webserver=args.webserver,
        selected_database=args.database,
        expected_web_image=expected_web_image,
        database_targets=database_targets,
    )
    write_file(output / "migration-automation.md", "\n".join(plan_lines) + "\n")

    common = (
        "#!/usr/bin/env bash\n"
        "set -euo pipefail\n"
        f'PROJECT_PATH="${{PROJECT_PATH:-{project_path}}}"\n'
        f'VALUES="${{VALUES:-{args.values}}}"\n'
        f'NAMESPACE="${{NAMESPACE:-{args.namespace}}}"\n'
        f'MIGRATION_OUTPUT="${{MIGRATION_OUTPUT:-{output}}}"\n'
        f'MIGRATION_PRIVATE_DIR="${{MIGRATION_PRIVATE_DIR:-{args.private_dir}}}"\n'
        f'MIGRATION_KUBECONFIG="${{MIGRATION_KUBECONFIG:-{args.kubeconfig}}}"\n'
        f'MIGRATION_INGRESS_HOST="${{MIGRATION_INGRESS_HOST:-{args.ingress_host}}}"\n'
        f'MIGRATION_TLS_CERT_FILE="${{MIGRATION_TLS_CERT_FILE:-{args.tls_cert_file}}}"\n'
        f'MIGRATION_TLS_KEY_FILE="${{MIGRATION_TLS_KEY_FILE:-{args.tls_key_file}}}"\n'
        f'MIGRATION_IMAGE_MODE="${{MIGRATION_IMAGE_MODE:-{args.image_mode}}}"\n'
        f'MIGRATION_IMAGE_OUTPUT_DIR="${{MIGRATION_IMAGE_OUTPUT_DIR:-{args.image_output_dir}}}"\n'
        f'MIGRATION_RKE2_NODES="${{MIGRATION_RKE2_NODES:-{args.rke2_nodes}}}"\n'
        f'MIGRATION_RKE2_IMAGE_DIR="${{MIGRATION_RKE2_IMAGE_DIR:-{args.rke2_image_dir}}}"\n'
        f'MIGRATION_SSH_USER="${{MIGRATION_SSH_USER:-{args.ssh_user}}}"\n'
        f'MIGRATION_SSH_KEY="${{MIGRATION_SSH_KEY:-{args.ssh_key}}}"\n'
        f'MIGRATION_BECOME_PASSWORD_FILE="${{MIGRATION_BECOME_PASSWORD_FILE:-{args.become_password_file}}}"\n'
        f'MIGRATION_CONTAINER_TOOL="${{MIGRATION_CONTAINER_TOOL:-{args.container_tool}}}"\n'
        f'MIGRATION_RKE2_IMPORT_IMAGES="${{MIGRATION_RKE2_IMPORT_IMAGES:-{str(args.rke2_import_images).lower()}}}"\n'
        f'MIGRATION_CLEANUP_OPERATOR_IMAGES="${{MIGRATION_CLEANUP_OPERATOR_IMAGES:-{str(args.cleanup_operator_images).lower()}}}"\n'
        f'MIGRATION_SKIP_DOCKER_SOCKET_SERVICES="${{MIGRATION_SKIP_DOCKER_SOCKET_SERVICES:-{str(args.skip_docker_socket_services).lower()}}}"\n'
        f'MIGRATION_REGISTRY="${{MIGRATION_REGISTRY:-{args.registry}}}"\n'
        f'MIGRATION_IMAGE_TAG="${{MIGRATION_IMAGE_TAG:-{args.image_tag}}}"\n'
        f'MIGRATION_DUMP_DIR="${{MIGRATION_DUMP_DIR:-{args.dump_dir}}}"\n'
        f'MIGRATION_DB_TARGETS="${{MIGRATION_DB_TARGETS:-{args.db_targets or ""}}}"\n'
        f'MIGRATION_ALLOW_SECRET_MATERIAL="${{MIGRATION_ALLOW_SECRET_MATERIAL:-{str(args.allow_secret_material).lower()}}}"\n'
        'ALLOW_FLAG=""\n'
        'if [ "$MIGRATION_ALLOW_SECRET_MATERIAL" = "true" ]; then ALLOW_FLAG="--allow-secret-material"; fi\n'
        'RKE2_IMPORT_FLAG="--rke2-import-images"\n'
        'if [ "$MIGRATION_RKE2_IMPORT_IMAGES" = "false" ]; then RKE2_IMPORT_FLAG="--no-rke2-import-images"; fi\n'
        'CLEANUP_OPERATOR_IMAGES_FLAG="--cleanup-operator-images"\n'
        'if [ "$MIGRATION_CLEANUP_OPERATOR_IMAGES" = "false" ]; then CLEANUP_OPERATOR_IMAGES_FLAG="--no-cleanup-operator-images"; fi\n'
        'DOCKER_SOCKET_FLAG="--skip-docker-socket-services"\n'
        'if [ "$MIGRATION_SKIP_DOCKER_SOCKET_SERVICES" = "false" ]; then DOCKER_SOCKET_FLAG="--include-docker-socket-services"; fi\n'
    )
    callback = (
        'python3 "$REPO_ROOT/scripts/migrate_project.py" '
        '--project-path "$PROJECT_PATH" --values "$VALUES" --namespace "$NAMESPACE" '
        '--output "$MIGRATION_OUTPUT" --private-dir "$MIGRATION_PRIVATE_DIR" --kubeconfig "$MIGRATION_KUBECONFIG" --auto-prepare '
        '--ingress-host "$MIGRATION_INGRESS_HOST" --tls-cert-file "$MIGRATION_TLS_CERT_FILE" --tls-key-file "$MIGRATION_TLS_KEY_FILE" '
        '--image-mode "$MIGRATION_IMAGE_MODE" --image-output-dir "$MIGRATION_IMAGE_OUTPUT_DIR" '
        '--rke2-nodes "$MIGRATION_RKE2_NODES" --rke2-image-dir "$MIGRATION_RKE2_IMAGE_DIR" '
        '--ssh-user "$MIGRATION_SSH_USER" --ssh-key "$MIGRATION_SSH_KEY" '
        '--become-password-file "$MIGRATION_BECOME_PASSWORD_FILE" '
        '--container-tool "$MIGRATION_CONTAINER_TOOL" '
        '$RKE2_IMPORT_FLAG $CLEANUP_OPERATOR_IMAGES_FLAG $DOCKER_SOCKET_FLAG '
        '--registry "$MIGRATION_REGISTRY" --image-tag "$MIGRATION_IMAGE_TAG" '
        '--dump-dir "$MIGRATION_DUMP_DIR" --db-targets "$MIGRATION_DB_TARGETS" '
        '--execute $ALLOW_FLAG '
    )
    write_file(
        output / "run-migration.sh",
        common
        + 'REPO_ROOT="${REPO_ROOT:-'
        + str(ROOT)
        + '}"\n'
        + f"{callback}--stage secrets\n"
        + f"{callback}--stage images\n"
        + f"{callback}--stage databases\n"
        + f"{callback}--stage manifests\n"
        + f"{callback}--stage validate\n",
        executable=True,
    )
    stage_scripts = {
        "01-sync-secrets.sh": "secrets",
        "02-build-and-push-images.sh": "images",
        "03-database-dump-restore.sh": "databases",
        "04-generate-routing-and-storage.sh": "manifests",
        "05-validate.sh": "validate",
    }
    for script_name, stage in stage_scripts.items():
        write_file(
            output / "scripts" / script_name,
            common
            + 'REPO_ROOT="${REPO_ROOT:-'
            + str(ROOT)
            + '}"\n'
            + f"{callback}--stage {stage}\n",
            executable=True,
        )

    db_target_example = {
        "databaseTargets": {
            "service-name-or-alias": {
                "host": "target-service-rw.namespace.svc",
                "port": 5432,
                "database": "target_db",
                "secretRef": {
                    "name": "target-service-app",
                    "namespace": "namespace",
                    "usernameKey": "username",
                    "passwordKey": "password",
                },
            }
        }
    }
    write_file(output / "db-targets.example.yaml", yaml.safe_dump(db_target_example, sort_keys=False))
    print(f"Migration automation bundle written to {output}")


def stage_secrets(args: argparse.Namespace, service_pairs: list[tuple[import_project.ServiceRecord, dict[str, Any]]]) -> None:
    secrets = []
    for record, service in service_pairs:
        entries = secret_entries(service)
        if entries:
            secrets.append((record, entries))
    print(f"Secret-bearing services: {len(secrets)}")
    if not args.execute:
        return
    if not args.allow_secret_material:
        raise SystemExit("Refusing to read/apply secret material without --allow-secret-material.")
    for record, entries in secrets:
        manifest = {
            "apiVersion": "v1",
            "kind": "Secret",
            "metadata": {
                "name": k8s_name(record.name, "import-env"),
                "namespace": args.namespace,
                "labels": {"app.kubernetes.io/managed-by": "urban-platform-import"},
            },
            "type": "Opaque",
            "stringData": entries,
        }
        run_command(kubectl_command(args, ["-n", args.namespace, "apply", "--validate=false", "-f", "-"]), stdin=yaml.safe_dump(manifest, sort_keys=False))


def stage_images(args: argparse.Namespace, project_path: Path, service_pairs: list[tuple[import_project.ServiceRecord, dict[str, Any]]]) -> None:
    candidates = []
    for record, service in service_pairs:
        if args.skip_docker_socket_services and service_has_docker_socket(service):
            print(f"Skipping Docker-socket service image candidate: {record.file}::{record.name}")
            continue
        if record.kind != "application" and not record.build_only:
            continue
        image = record.image
        build = service.get("build")
        needs_tag = record.build_only or (image is not None and (not image.tag or image.tag in import_project.MUTABLE_TAGS))
        if needs_tag:
            candidates.append((record, service, build))
    print(f"Application image promotion candidates: {len(candidates)}")
    if not args.execute:
        return
    if args.image_mode == "skip":
        print("Image migration skipped by MIGRATION_IMAGE_MODE=skip. Keep these services on Compose or provide images another way.")
        return
    if args.image_mode == "registry" and not args.registry:
        raise SystemExit("Refusing image promotion without --registry or MIGRATION_REGISTRY.")
    print(f"Using container CLI for image migration: {container_tool(args)}")
    ensure_registry_login(args)
    archive_dir = Path(args.image_output_dir).expanduser()
    if args.image_mode == "preload":
        archive_dir.mkdir(parents=True, exist_ok=True)
        print("Preload mode stages images on the operator, then copies and verifies archives on the RKE2 nodes.")
    skipped: list[str] = []
    failed: list[str] = []
    generated_images: list[str] = []
    pulled_source_images: list[str] = []
    for record, service, build in candidates:
        target_image = local_import_image(args, record)
        compose_path = relative_compose_file(project_path, record.file)
        try:
            if build:
                context, dockerfile, fallback_note = resolve_build_source(compose_path, build)
                if fallback_note:
                    print(fallback_note)
                if not context.exists() or not context.is_dir():
                    skipped.append(f"{record.file}::{record.name} (build context does not exist: {context})")
                    continue
                dockerfile_path = (context / dockerfile).resolve()
                if not dockerfile_path.exists() or not dockerfile_path.is_file():
                    skipped.append(f"{record.file}::{record.name} (Dockerfile does not exist: {dockerfile_path})")
                    continue
                run_command(container_command(args, "build", "-t", target_image, "-f", dockerfile, "."), cwd=context)
            elif record.image:
                source_ready, source_cleanup_images = ensure_source_image(args, record)
                if not source_ready:
                    skipped.append(f"{record.file}::{record.name} ({record.image.display})")
                    continue
                pulled_source_images.extend(source_cleanup_images)
                run_command(container_command(args, "tag", record.image.display, target_image))
            generated_images.append(target_image)
            if args.image_mode == "registry":
                run_command(container_command(args, "push", target_image))
            elif args.image_mode == "preload":
                archive_path = archive_dir / image_archive_name(record)
                if archive_path.exists():
                    archive_path.unlink()
                run_command(container_command(args, "save", "-o", str(archive_path), target_image))
            if args.cleanup_operator_images:
                cleanup_operator_container_tags(args, [target_image])
        except subprocess.CalledProcessError as exc:
            failed.append(f"{record.file}::{record.name} ({exc.cmd})")
    if args.image_mode == "preload":
        archives_copied = preload_archives_to_nodes(args, archive_dir)
        if args.cleanup_operator_images and archives_copied:
            cleanup_operator_archives(archive_dir)
    if args.cleanup_operator_images:
        cleanup_operator_container_tags(args, generated_images + pulled_source_images)
    if skipped:
        print("Skipped image candidates:")
        for item in skipped:
            print(f"- {item}")
    if failed:
        print("Failed image candidates:")
        for item in failed:
            print(f"- {item}")
        raise SystemExit(f"Image migration completed with {len(failed)} failed candidate(s).")


def stage_databases(args: argparse.Namespace, service_pairs: list[tuple[import_project.ServiceRecord, dict[str, Any]]]) -> None:
    db_targets_path = args.db_targets or str(Path(args.private_dir).expanduser() / "db-targets.yaml")
    targets = read_database_targets(db_targets_path)
    dump_dir = Path(args.dump_dir).expanduser()
    candidates = [
        (record, service)
        for record, service in service_pairs
        if record.kind in {"postgresql", "postgis", "timescaledb"}
    ]
    print(f"PostgreSQL-family migration candidates: {len(candidates)}")
    if not args.execute:
        return
    if not args.allow_secret_material:
        raise SystemExit("Refusing database dump/restore without --allow-secret-material.")
    dump_dir.mkdir(parents=True, exist_ok=True)
    for record, service in candidates:
        port = published_port(record)
        env = postgres_env(service)
        if not port or not env["password"]:
            print(f"Skipping {record.file}::{record.name}: missing published port or POSTGRES_PASSWORD.")
            continue
        alias = k8s_name(record.name)
        dump_file = dump_dir / f"{alias}.dump"
        run_env = os.environ.copy()
        run_env["PGPASSWORD"] = env["password"]
        run_command(
            [
                "pg_dump",
                "--format=custom",
                "--no-owner",
                "--no-acl",
                "--host",
                "127.0.0.1",
                "--port",
                port,
                "--username",
                env["user"],
                "--dbname",
                env["database"],
                "--file",
                str(dump_file),
            ],
            env=run_env,
        )
        target_dsn = target_dsn_from_mapping(targets.get(record.name) or targets.get(alias), args.namespace, args.kubeconfig)
        if target_dsn:
            restore_env = os.environ.copy()
            run_command(
                [
                    "pg_restore",
                    "--clean",
                    "--if-exists",
                    "--no-owner",
                    "--dbname",
                    target_dsn,
                    str(dump_file),
                ],
                env=restore_env,
            )
        else:
            print(f"Dumped {alias}; no usable target mapping found in {db_targets_path}, so restore was skipped.")


def ingress_host(args: argparse.Namespace, values: dict[str, Any]) -> str:
    return str(
        args.ingress_host
        or values.get("ingress", {}).get("host", "")
        or values.get("global", {}).get("cluster", {}).get("domain", "")
    )


def ingress_tls_secret_name(values: dict[str, Any]) -> str:
    return str(values.get("ingress", {}).get("tls", {}).get("secretName") or "urban-platform-tls")


def kubernetes_secret_exists(args: argparse.Namespace, name: str) -> bool:
    command = kubectl_command(args, ["-n", args.namespace, "get", "secret", name, "--request-timeout=15s"])
    return subprocess.run(command, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL).returncode == 0


def ingress_san(host: str) -> str:
    try:
        ipaddress.ip_address(host)
    except ValueError:
        return f"DNS:{host}"
    return f"IP:{host}"


def apply_tls_secret_from_files(args: argparse.Namespace, name: str, cert_file: Path, key_file: Path) -> None:
    create_command = kubectl_command(
        args,
        [
            "-n",
            args.namespace,
            "create",
            "secret",
            "tls",
            name,
            "--cert",
            str(cert_file),
            "--key",
            str(key_file),
            "--dry-run=client",
            "-o",
            "yaml",
        ],
    )
    result = subprocess.run(create_command, text=True, capture_output=True, check=True)
    run_command(kubectl_command(args, ["-n", args.namespace, "apply", "--validate=false", "-f", "-"]), stdin=result.stdout)


def ensure_ingress_tls_secret(args: argparse.Namespace, values: dict[str, Any], host: str) -> None:
    tls_values = values.get("ingress", {}).get("tls", {})
    if not tls_values.get("enabled", True):
        return
    secret_name = ingress_tls_secret_name(values)
    if kubernetes_secret_exists(args, secret_name):
        print(f"Ingress TLS secret already exists: {secret_name}")
        return

    cert_file_arg = args.tls_cert_file
    key_file_arg = args.tls_key_file
    if cert_file_arg or key_file_arg:
        if not cert_file_arg or not key_file_arg:
            raise SystemExit("Both MIGRATION_TLS_CERT_FILE and MIGRATION_TLS_KEY_FILE are required when providing an ingress certificate.")
        cert_file = Path(cert_file_arg).expanduser()
        key_file = Path(key_file_arg).expanduser()
        if not cert_file.is_file() or not key_file.is_file():
            raise SystemExit(f"Provided ingress TLS files were not found: cert={cert_file} key={key_file}")
        print(f"Creating ingress TLS secret {secret_name} from provided certificate files.")
        apply_tls_secret_from_files(args, secret_name, cert_file, key_file)
        return

    if not host:
        raise SystemExit("Cannot create a self-signed ingress certificate without MIGRATION_INGRESS_HOST, MIGRATION_CLUSTER_DOMAIN, ingress.host, or global.cluster.domain.")
    if not shutil.which("openssl"):
        raise SystemExit("Cannot create default self-signed ingress certificate because `openssl` is not installed on the operator machine.")

    duration_days = int(tls_values.get("selfSigned", {}).get("durationDays", 3650))
    with tempfile.TemporaryDirectory(prefix="urban-platform-tls-") as tmp_dir:
        cert_file = Path(tmp_dir) / "tls.crt"
        key_file = Path(tmp_dir) / "tls.key"
        run_command(
            [
                "openssl",
                "req",
                "-x509",
                "-nodes",
                "-newkey",
                "rsa:2048",
                "-days",
                str(duration_days),
                "-subj",
                f"/CN={host}",
                "-addext",
                f"subjectAltName={ingress_san(host)}",
                "-keyout",
                str(key_file),
                "-out",
                str(cert_file),
            ]
        )
        print(f"Creating self-signed ingress TLS secret {secret_name} for {host}.")
        apply_tls_secret_from_files(args, secret_name, cert_file, key_file)


def stage_manifests(args: argparse.Namespace, service_pairs: list[tuple[import_project.ServiceRecord, dict[str, Any]]], values: dict[str, Any]) -> None:
    output = Path(args.output).expanduser()
    manifests: list[dict[str, Any]] = []
    host = ingress_host(args, values)
    tls_enabled = bool(values.get("ingress", {}).get("tls", {}).get("enabled", True))
    tls_secret_name = ingress_tls_secret_name(values)
    for record, service in service_pairs:
        if record.kind == "nginx" and import_project.has_edge_publish(record.ports):
            name = k8s_name(record.name)
            rule: dict[str, Any] = {
                "http": {
                    "paths": [
                        {
                            "path": "/",
                            "pathType": "Prefix",
                            "backend": {
                                "service": {"name": name, "port": {"number": 80}}
                            },
                        }
                    ]
                }
            }
            if host:
                rule["host"] = host
            spec: dict[str, Any] = {
                "ingressClassName": "traefik",
                "rules": [rule],
            }
            annotations = {"traefik.ingress.kubernetes.io/router.entrypoints": "websecure"}
            if tls_enabled:
                tls_entry: dict[str, Any] = {"secretName": tls_secret_name}
                if host:
                    tls_entry["hosts"] = [host]
                spec["tls"] = [tls_entry]
                annotations["traefik.ingress.kubernetes.io/router.tls"] = "true"
            manifests.append(
                {
                    "apiVersion": "networking.k8s.io/v1",
                    "kind": "Ingress",
                    "metadata": {
                        "name": f"{name}-traefik",
                        "namespace": args.namespace,
                        "annotations": annotations,
                    },
                    "spec": spec,
                }
            )
    content = GENERATED_HEADER + yaml.safe_dump_all(manifests, sort_keys=False)
    path = output / "manifests" / "traefik-ingress-candidates.yaml"
    write_file(path, content)
    print(f"Wrote {path}")
    if args.execute and manifests:
        ensure_ingress_tls_secret(args, values, host)
        run_command(kubectl_command(args, ["-n", args.namespace, "apply", "--validate=false", "-f", str(path)]))


def stage_validate(args: argparse.Namespace) -> None:
    command = [
        "python3",
        str(ROOT / "scripts/import_project.py"),
        "--project-path",
        args.project_path,
        "--values",
        args.values,
        "--ingress-controller",
        args.ingress_controller,
        "--webserver",
        args.webserver,
        "--database",
        args.database,
        "--report",
        str(Path(args.output).expanduser() / "post-migration-check.md"),
    ]
    if args.redact_sensitive:
        command.append("--redact-sensitive")
    if args.allow_secret_material:
        command.append("--allow-literal-secret-import")
    if args.skip_docker_socket_services:
        command.append("--allow-docker-socket-skip")
    if args.execute:
        run_command(command)
    else:
        print("Validation command:")
        print(" ".join(command))


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate or execute guarded project migration automation.")
    parser.add_argument("--project-path", required=True)
    parser.add_argument("--values", default=str(DEFAULT_VALUES))
    parser.add_argument("--image-policy", default=str(import_project.DEFAULT_IMAGE_POLICY))
    parser.add_argument("--output", default="reports/import-migration")
    parser.add_argument("--namespace", default="urban-platform")
    parser.add_argument("--kubeconfig", default=os.environ.get("KUBECONFIG", ""))
    parser.add_argument("--ingress-host", default=os.environ.get("MIGRATION_INGRESS_HOST", os.environ.get("MIGRATION_CLUSTER_DOMAIN", "")))
    parser.add_argument("--tls-cert-file", default=os.environ.get("MIGRATION_TLS_CERT_FILE", ""))
    parser.add_argument("--tls-key-file", default=os.environ.get("MIGRATION_TLS_KEY_FILE", ""))
    parser.add_argument("--ingress-controller", choices=["traefik", "nginx"], default="traefik")
    parser.add_argument("--webserver", choices=["nginx", "apache-httpd", "apache-tomcat", "traefik"], default="nginx")
    parser.add_argument("--database", default="postgresql")
    parser.add_argument("--image-mode", choices=["registry", "preload", "skip"], default="registry")
    parser.add_argument("--image-output-dir", default="/var/lib/urban-platform/private/images")
    parser.add_argument("--rke2-nodes", default="")
    parser.add_argument("--rke2-image-dir", default="/var/lib/rancher/rke2/agent/images")
    parser.add_argument("--ssh-user", default="root")
    parser.add_argument("--ssh-key", default="")
    parser.add_argument("--become-password-file", default=os.environ.get("MIGRATION_BECOME_PASSWORD_FILE", ""))
    parser.add_argument("--container-tool", default=os.environ.get("MIGRATION_CONTAINER_TOOL", "auto"))
    parser.add_argument("--rke2-import-images", dest="rke2_import_images", action="store_true", default=True)
    parser.add_argument("--no-rke2-import-images", dest="rke2_import_images", action="store_false")
    parser.add_argument("--cleanup-operator-images", dest="cleanup_operator_images", action="store_true", default=True)
    parser.add_argument("--no-cleanup-operator-images", dest="cleanup_operator_images", action="store_false")
    parser.add_argument("--skip-docker-socket-services", dest="skip_docker_socket_services", action="store_true", default=True)
    parser.add_argument("--include-docker-socket-services", dest="skip_docker_socket_services", action="store_false")
    parser.add_argument("--registry", default="")
    parser.add_argument("--image-tag", default="imported-0.1.0")
    parser.add_argument("--private-dir", default=str(DEFAULT_PRIVATE_DIR))
    parser.add_argument("--dump-dir", default="/var/lib/urban-platform/private/db-dumps")
    parser.add_argument("--db-targets", default="")
    parser.add_argument("--stage", choices=["prepare", "bundle", "secrets", "images", "databases", "manifests", "validate", "all"], default="bundle")
    parser.add_argument("--auto-prepare", action="store_true")
    parser.add_argument("--execute", action="store_true")
    parser.add_argument("--allow-secret-material", action="store_true")
    parser.add_argument("--redact-sensitive", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    project_path, compose_files, service_pairs, findings, values = load_context(args)
    if args.auto_prepare and args.stage != "prepare":
        stage_prepare(args, project_path, compose_files, service_pairs, findings, values)
    if args.stage == "prepare":
        stage_prepare(args, project_path, compose_files, service_pairs, findings, values)
    if args.execute and args.stage in {"secrets", "images", "databases", "manifests", "validate", "all"}:
        fail_on_unhandled_errors(args, findings)
    if args.stage in {"bundle", "all"}:
        generate_bundle(args, project_path, service_pairs, findings, values)
        print_bundle_files(Path(args.output).expanduser())
        if args.stage == "bundle" and args.execute:
            print("Execute mode was set, but stage `bundle` only writes automation files. Use --stage all or a specific --stage to run actions.")
    if args.stage in {"secrets", "databases", "manifests", "all"}:
        require_kubernetes_api(args)
    if args.stage in {"secrets", "all"}:
        stage_secrets(args, service_pairs)
    if args.stage in {"images", "all"}:
        stage_images(args, project_path, service_pairs)
    if args.stage in {"databases", "all"}:
        stage_databases(args, service_pairs)
    if args.stage in {"manifests", "all"}:
        stage_manifests(args, service_pairs, values)
    if args.stage in {"validate", "all"}:
        stage_validate(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
