#!/usr/bin/env python3
"""Generate and execute guarded Compose-to-platform migration automation."""
from __future__ import annotations

import argparse
import base64
import hashlib
import json
import os
import re
import shlex
import stat
import subprocess
import sys
from pathlib import Path
from typing import Any
from urllib.parse import quote

try:
    import yaml
except ModuleNotFoundError:  # pragma: no cover - exercised by operator setup.
    yaml = None

import import_project


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_VALUES = ROOT / "helm/urban-platform-infra/values.yaml"
DEFAULT_PRIVATE_DIR = Path("/var/lib/urban-platform/private")
SECRET_ENV_RE = import_project.SECRET_KEY_RE
GENERATED_HEADER = "# Generated by scripts/migrate_project.py. Keep private outputs out of Git.\n"


def require_yaml() -> None:
    if yaml is None:
        raise SystemExit("PyYAML is required. Install it with `python3 -m pip install PyYAML`.")


def k8s_name(value: str, prefix: str = "") -> str:
    safe = re.sub(r"[^a-z0-9-]+", "-", value.lower()).strip("-")
    safe = re.sub(r"-+", "-", safe) or "item"
    digest = hashlib.sha256(value.encode("utf-8")).hexdigest()[:8]
    base = f"{prefix}-{safe}" if prefix else safe
    base = base[:52].strip("-")
    return f"{base}-{digest}"[:63].strip("-")


def relative_compose_file(project_path: Path, file_name: str) -> Path:
    return project_path / file_name


def load_context(args: argparse.Namespace) -> tuple[Path, list[Path], list[tuple[import_project.ServiceRecord, dict[str, Any]]], list[import_project.Finding], dict[str, Any]]:
    require_yaml()
    project_path = Path(args.project_path).expanduser().resolve()
    if not project_path.exists() or not project_path.is_dir():
        raise SystemExit(f"Project path does not exist or is not a directory: {project_path}")

    values_path = Path(args.values).expanduser()
    if not values_path.is_absolute():
        values_path = (ROOT / values_path).resolve()
    policy_path = Path(args.image_policy).expanduser()
    if not policy_path.is_absolute():
        policy_path = (ROOT / policy_path).resolve()

    values = import_project.load_yaml(values_path)
    approved_images = import_project.normalize_approved_images(policy_path)
    selected_ingress = args.ingress_controller or values.get("ingress", {}).get("className", "traefik")
    selected_webserver = args.webserver or values.get("webserver", {}).get("provider", "nginx")
    selected_database = args.database or values.get("databases", {}).get("provider", "cloudnative-pg")
    expected_web_image = import_project.expected_webserver_image(values, selected_webserver)

    findings: list[import_project.Finding] = []
    compose_files = import_project.find_compose_files(project_path)
    service_pairs = import_project.read_compose_services(project_path, compose_files, findings)
    for record, service in service_pairs:
        import_project.analyze_service(
            service=service,
            record=record,
            findings=findings,
            approved_images=approved_images,
            selected_ingress=str(selected_ingress),
            selected_webserver=str(selected_webserver),
            selected_database=str(selected_database),
            expected_web_image=expected_web_image,
        )
    return project_path, compose_files, service_pairs, findings, values


def secret_entries(service: dict[str, Any]) -> dict[str, str]:
    entries: dict[str, str] = {}
    for key, value in import_project.environment_entries(service.get("environment")):
        if not SECRET_ENV_RE.search(key):
            continue
        if value is None or import_project.VARIABLE_VALUE_RE.match(value):
            continue
        entries[key] = value
    return entries


def postgres_env(service: dict[str, Any]) -> dict[str, str]:
    env = {key: value for key, value in import_project.environment_entries(service.get("environment")) if value is not None}
    return {
        "user": env.get("POSTGRES_USER", "postgres"),
        "password": env.get("POSTGRES_PASSWORD", ""),
        "database": env.get("POSTGRES_DB", env.get("POSTGRES_USER", "postgres")),
    }


def published_port(record: import_project.ServiceRecord, target: str = "5432") -> str | None:
    for port in record.ports:
        if port.target == target and port.published:
            return port.published
    return None


def read_database_targets(path: str | None) -> dict[str, Any]:
    if not path:
        return {}
    target_path = Path(path).expanduser()
    if not target_path.exists():
        raise SystemExit(f"Database target map does not exist: {target_path}")
    data = yaml.safe_load(target_path.read_text(encoding="utf-8")) or {}
    targets = data.get("databaseTargets", data)
    if not isinstance(targets, dict):
        raise SystemExit("Database target map must be a mapping or contain `databaseTargets`.")
    return {str(key): value for key, value in targets.items()}


def k8s_secret_data(namespace: str, name: str) -> dict[str, str]:
    result = subprocess.run(
        ["kubectl", "-n", namespace, "get", "secret", name, "-o", "json"],
        text=True,
        capture_output=True,
        check=True,
    )
    payload = json.loads(result.stdout)
    encoded_data = payload.get("data", {})
    return {
        key: base64.b64decode(value).decode("utf-8")
        for key, value in encoded_data.items()
    }


def target_dsn_from_mapping(target: Any, namespace: str) -> str | None:
    if isinstance(target, str):
        if any(marker in target for marker in ["<target_", "<namespace>"]):
            return None
        return target
    if not isinstance(target, dict):
        return None

    host = target.get("host")
    database = target.get("database")
    port = target.get("port", 5432)
    username = target.get("username")
    password = target.get("password")
    secret_ref = target.get("secretRef") or target.get("secret")
    if isinstance(secret_ref, dict) and (not username or not password):
        secret_namespace = str(secret_ref.get("namespace") or namespace)
        secret_name = str(secret_ref.get("name"))
        try:
            secret_data = k8s_secret_data(secret_namespace, secret_name)
        except subprocess.CalledProcessError:
            print(f"Could not read target database secret {secret_namespace}/{secret_name}; restore for this target will be skipped.")
            return None
        username = secret_data.get(str(secret_ref.get("usernameKey", "username")))
        password = password or secret_data.get(str(secret_ref.get("passwordKey", "password")))
        database = database or secret_data.get(str(secret_ref.get("databaseKey", "dbname")))
        host = host or secret_data.get(str(secret_ref.get("hostKey", "host")))
        port = target.get("port") or secret_data.get(str(secret_ref.get("portKey", "port")), 5432)
    if not host or not database or not username or not password:
        return None
    if str(password).startswith("<") or str(username).startswith("<") or str(database).startswith("<"):
        return None
    return f"postgresql://{quote(str(username), safe='')}:{quote(str(password), safe='')}@{host}:{port}/{quote(str(database), safe='')}"


def run_command(command: list[str], *, env: dict[str, str] | None = None, stdin: str | None = None, cwd: Path | None = None) -> None:
    display = " ".join(command)
    print(f"+ {display}")
    subprocess.run(command, input=stdin, text=True, env=env, cwd=str(cwd) if cwd else None, check=True)


def write_file(path: Path, content: str, executable: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    if executable:
        path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP)


def secure_directory(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)
    try:
        path.chmod(0o700)
    except PermissionError:
        print(f"Could not chmod {path}; verify permissions manually.")


def secure_file(path: Path) -> None:
    try:
        path.chmod(0o600)
    except PermissionError:
        print(f"Could not chmod {path}; verify permissions manually.")


def registry_host(registry: str) -> str:
    return registry.split("/", 1)[0]


def ensure_registry_login(args: argparse.Namespace) -> None:
    if not args.execute or args.image_mode != "registry" or not args.registry:
        return
    username = os.environ.get("MIGRATION_REGISTRY_USERNAME")
    password = os.environ.get("MIGRATION_REGISTRY_PASSWORD")
    if not username or not password:
        print("Registry credentials were not provided in MIGRATION_REGISTRY_USERNAME/MIGRATION_REGISTRY_PASSWORD; using existing Docker login state.")
        return
    run_command(["docker", "login", registry_host(args.registry), "--username", username, "--password-stdin"], stdin=password)


def image_archive_name(record: import_project.ServiceRecord) -> str:
    return f"{k8s_name(record.name)}.tar"


def local_import_image(args: argparse.Namespace, record: import_project.ServiceRecord) -> str:
    if args.registry:
        return f"{args.registry.rstrip('/')}/{k8s_name(record.name)}:{args.image_tag}"
    return f"urban-platform-import/{k8s_name(record.name)}:{args.image_tag}"


def docker_image_exists(image: str) -> bool:
    return subprocess.run(["docker", "image", "inspect", image], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL).returncode == 0


def pullable_image(image: import_project.ImageRef) -> bool:
    if image.variable:
        return False
    first_segment = image.repository.split("/", 1)[0]
    return "/" in image.repository or "." in first_segment or ":" in first_segment


def ensure_source_image(record: import_project.ServiceRecord) -> bool:
    if record.image is None:
        return False
    source = record.image.display
    if docker_image_exists(source):
        return True
    if pullable_image(record.image):
        print(f"Source image {source} is not local; pulling it before import.")
        pull = subprocess.run(["docker", "pull", source])
        return pull.returncode == 0
    print(f"Source image {source} is not local and does not look pullable; skipping {record.name}.")
    return False


def preload_archives_to_nodes(args: argparse.Namespace, archive_dir: Path) -> None:
    nodes = [node.strip() for node in args.rke2_nodes.split(",") if node.strip()]
    archives = sorted(archive_dir.glob("*.tar"))
    if not archives:
        print(f"No image archives were written to {archive_dir}.")
        return
    if not nodes:
        print(f"Image archives written to {archive_dir}. Set MIGRATION_RKE2_NODES to copy them to RKE2 nodes automatically.")
        return
    ssh_target_prefix = f"{args.ssh_user}@"
    ssh_options: list[str] = []
    if args.ssh_key:
        ssh_options.extend(["-i", args.ssh_key])
    remote_tmp = "/tmp/urban-platform-import-images"
    remote_image_dir = shlex.quote(args.rke2_image_dir)
    for node in nodes:
        target = node if "@" in node else f"{ssh_target_prefix}{node}"
        run_command(["ssh", *ssh_options, target, f"mkdir -p {remote_tmp}"])
        for archive in archives:
            run_command(["scp", *ssh_options, str(archive), f"{target}:{remote_tmp}/"])
        run_command(
            [
                "ssh",
                *ssh_options,
                target,
                f"sudo mkdir -p {args.rke2_image_dir} && sudo cp {remote_tmp}/*.tar {args.rke2_image_dir}/",
            ]
        )
        archive_checks = " ".join(shlex.quote(f"{args.rke2_image_dir}/{archive.name}") for archive in archives)
        run_command(["ssh", *ssh_options, target, f"sudo sh -lc 'for archive in {archive_checks}; do test -s \"$archive\"; done'"])
        if args.rke2_import_images:
            import_preloaded_archives_to_containerd(args, ssh_options, target, remote_image_dir)


def import_preloaded_archives_to_containerd(args: argparse.Namespace, ssh_options: list[str], target: str, remote_image_dir: str) -> None:
    script = (
        "set -e; "
        "ctr=/var/lib/rancher/rke2/bin/ctr; "
        "socket=/run/k3s/containerd/containerd.sock; "
        f"image_dir={remote_image_dir}; "
        "if [ -S \"$socket\" ] && [ -x \"$ctr\" ]; then "
        "for archive in \"$image_dir\"/*.tar; do "
        "[ -e \"$archive\" ] || continue; "
        "\"$ctr\" --address \"$socket\" -n k8s.io images import \"$archive\"; "
        "done; "
        "\"$ctr\" --address \"$socket\" -n k8s.io images ls >/dev/null; "
        "echo \"Imported preload archives into running RKE2 containerd.\"; "
        "else "
        "echo \"RKE2 containerd is not running on this node; archives are present for startup import.\"; "
        "fi"
    )
    run_command(["ssh", *ssh_options, target, f"sudo sh -lc {shlex.quote(script)}"])


def database_instances(values: dict[str, Any], namespace: str) -> list[dict[str, Any]]:
    instances = values.get("databases", {}).get("instances", {})
    targets: list[dict[str, Any]] = []
    for name, config in instances.items():
        if not isinstance(config, dict) or not config.get("enabled", False):
            continue
        engine = str(config.get("engine", "postgresql"))
        database = str(config.get("database", name))
        owner = str(config.get("owner", database))
        targets.append(
            {
                "name": str(name),
                "engine": engine,
                "host": f"{name}-rw.{namespace}.svc",
                "port": int(config.get("postgresPort", 5432)),
                "database": database,
                "owner": owner,
                "secretRef": {
                    "name": f"{name}-app",
                    "namespace": namespace,
                    "usernameKey": "username",
                    "passwordKey": "password",
                },
            }
        )
    return targets


def target_for_record(record: import_project.ServiceRecord, available: list[dict[str, Any]], index: int) -> dict[str, Any]:
    matching_index = next((i for i, target in enumerate(available) if target["engine"] == record.kind), None)
    if matching_index is None and record.kind == "postgresql":
        matching_index = next((i for i, target in enumerate(available) if target["engine"] in {"postgres", "postgresql"}), None)
    if matching_index is None and available:
        matching_index = 0
    if matching_index is None:
        return {
            "host": f"{k8s_name(record.name)}-rw.<namespace>.svc",
            "port": 5432,
            "database": "<target_database>",
            "username": "<target_user>",
            "password": "<target_password>",
        }
    return available.pop(matching_index)


def generated_database_targets(
    service_pairs: list[tuple[import_project.ServiceRecord, dict[str, Any]]],
    values: dict[str, Any],
    namespace: str,
) -> dict[str, Any]:
    available = database_instances(values, namespace)
    mapping: dict[str, Any] = {}
    database_records = [
        record
        for record, _service in service_pairs
        if record.kind in {"postgresql", "postgis", "timescaledb"}
    ]
    for index, record in enumerate(database_records):
        target = target_for_record(record, available, index)
        entry = {
            "sourceAlias": k8s_name(record.name),
            "targetService": target.get("name", "<target-service>"),
            "host": target["host"],
            "port": target["port"],
            "database": target["database"],
        }
        if target.get("secretRef"):
            entry["secretRef"] = target["secretRef"]
        if target.get("username"):
            entry["username"] = target["username"]
        if target.get("password"):
            entry["password"] = target["password"]
        mapping[record.name] = entry
    return {"databaseTargets": mapping}


def write_database_target_map(path: Path, service_pairs: list[tuple[import_project.ServiceRecord, dict[str, Any]]], values: dict[str, Any], namespace: str) -> None:
    should_replace_placeholder = False
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        should_replace_placeholder = "service-name-or-alias" in existing
    if path.exists() and not should_replace_placeholder:
        secure_file(path)
        print(f"Database target map already exists: {path}")
        return
    write_file(path, yaml.safe_dump(generated_database_targets(service_pairs, values, namespace), sort_keys=False))
    secure_file(path)
    print(f"Database target map initialized: {path}")


def render_private_report(
    args: argparse.Namespace,
    private_report: Path,
    project_path: Path,
    compose_files: list[Path],
    service_pairs: list[tuple[import_project.ServiceRecord, dict[str, Any]]],
    findings: list[import_project.Finding],
    values: dict[str, Any],
) -> None:
    report = import_project.render_report(
        project_path=project_path,
        compose_files=compose_files,
        service_records=[record for record, _service in service_pairs],
        findings=findings,
        selected_ingress=args.ingress_controller,
        selected_webserver=args.webserver,
        selected_database=args.database,
        expected_web_image=import_project.expected_webserver_image(values, args.webserver),
        database_targets=import_project.database_target_images(values),
        redact_sensitive=False,
    )
    write_file(private_report, report)
    secure_file(private_report)
    print(f"Private import report written: {private_report}")


def print_bundle_files(output: Path) -> None:
    if not output.exists():
        return
    print("Migration bundle files:")
    for path in sorted(item for item in output.rglob("*") if item.is_file()):
        print(f"- {path.relative_to(output)}")


def stage_prepare(
    args: argparse.Namespace,
    project_path: Path,
    compose_files: list[Path],
    service_pairs: list[tuple[import_project.ServiceRecord, dict[str, Any]]],
    findings: list[import_project.Finding],
    values: dict[str, Any],
) -> None:
    private_dir = Path(args.private_dir).expanduser()
    secure_directory(private_dir)
    secure_directory(Path(args.dump_dir).expanduser())
    db_targets_path = Path(args.db_targets).expanduser() if args.db_targets else private_dir / "db-targets.yaml"
    write_database_target_map(db_targets_path, service_pairs, values, args.namespace)
    render_private_report(
        args=args,
        private_report=private_dir / "import-check-private.md",
        project_path=project_path,
        compose_files=compose_files,
        service_pairs=service_pairs,
        findings=findings,
        values=values,
    )
    ensure_registry_login(args)


def generate_bundle(
    args: argparse.Namespace,
    project_path: Path,
    service_pairs: list[tuple[import_project.ServiceRecord, dict[str, Any]]],
    findings: list[import_project.Finding],
    values: dict[str, Any],
) -> None:
    output = Path(args.output).expanduser()
    output.mkdir(parents=True, exist_ok=True)
    redactor = import_project.ReportRedactor(args.redact_sensitive)
    service_records = [record for record, _service in service_pairs]
    database_targets = import_project.database_target_images(values)
    expected_web_image = import_project.expected_webserver_image(values, args.webserver)

    plan_lines = [
        "# Import Migration Automation",
        "",
        f"- Project path: `{redactor.project_path(project_path)}`",
        f"- Namespace: `{args.namespace}`",
        f"- Private registry: `{args.registry or 'not configured'}`",
        f"- Image tag: `{args.image_tag}`",
        f"- Private operator directory: `{args.private_dir}`",
        f"- Dump directory: `{args.dump_dir}`",
        f"- Database target map: `{args.db_targets or str(Path(args.private_dir).expanduser() / 'db-targets.yaml')}`",
        f"- Image mode: `{args.image_mode}`",
        f"- Auto prepare: `{str(args.auto_prepare).lower()}`",
        f"- Execute mode: `{str(args.execute).lower()}`",
        f"- Redacted output: `{str(args.redact_sensitive).lower()}`",
        "",
        "## Automation Entry Points",
        "",
        "- `run-migration.sh` runs all guarded stages.",
        "- Automatic preparation creates the private report, DB target map, dump directory, and optional registry login before guarded stages run.",
        "- `scripts/01-sync-secrets.sh` applies Kubernetes Secrets from Compose secret environment values when explicitly allowed.",
        "- `scripts/02-build-and-push-images.sh` builds application images. Use image mode `registry` to push, `preload` to export/copy tar archives to RKE2 nodes, or `skip` for external Compose transition mode.",
        "- `scripts/03-database-dump-restore.sh` dumps PostgreSQL-family sources and restores only targets defined in the private database target map.",
        "- `scripts/04-generate-routing-and-storage.sh` writes Traefik, ConfigMap, Secret, and PVC candidate manifests.",
        "- `scripts/05-validate.sh` re-runs the compatibility checker.",
        "",
        "## Guardrails",
        "",
        "- Dry-run is the default. Use `MIGRATION_EXECUTE=true` only on the trusted operator machine.",
        "- Secret and database stages require `MIGRATION_ALLOW_SECRET_MATERIAL=true` so secret values are read only at execution time.",
        "- Database restore uses the private `MIGRATION_DB_TARGETS` file. The generated map targets CloudNativePG app secrets when platform database instances exist.",
        "- Registry login is used only with image mode `registry`. Image mode `preload` avoids registry login by writing image archives and optionally copying them to RKE2 nodes.",
        "- Generated output must stay in `reports/` or another ignored/private directory.",
        "",
    ]
    import_project.render_migration_plan(
        lines=plan_lines,
        service_records=service_records,
        findings=findings,
        redactor=redactor,
        selected_ingress=args.ingress_controller,
        selected_webserver=args.webserver,
        selected_database=args.database,
        expected_web_image=expected_web_image,
        database_targets=database_targets,
    )
    write_file(output / "migration-automation.md", "\n".join(plan_lines) + "\n")

    common = (
        "#!/usr/bin/env bash\n"
        "set -euo pipefail\n"
        f'PROJECT_PATH="${{PROJECT_PATH:-{project_path}}}"\n'
        f'VALUES="${{VALUES:-{args.values}}}"\n'
        f'NAMESPACE="${{NAMESPACE:-{args.namespace}}}"\n'
        f'MIGRATION_OUTPUT="${{MIGRATION_OUTPUT:-{output}}}"\n'
        f'MIGRATION_PRIVATE_DIR="${{MIGRATION_PRIVATE_DIR:-{args.private_dir}}}"\n'
        f'MIGRATION_IMAGE_MODE="${{MIGRATION_IMAGE_MODE:-{args.image_mode}}}"\n'
        f'MIGRATION_IMAGE_OUTPUT_DIR="${{MIGRATION_IMAGE_OUTPUT_DIR:-{args.image_output_dir}}}"\n'
        f'MIGRATION_RKE2_NODES="${{MIGRATION_RKE2_NODES:-{args.rke2_nodes}}}"\n'
        f'MIGRATION_RKE2_IMAGE_DIR="${{MIGRATION_RKE2_IMAGE_DIR:-{args.rke2_image_dir}}}"\n'
        f'MIGRATION_SSH_USER="${{MIGRATION_SSH_USER:-{args.ssh_user}}}"\n'
        f'MIGRATION_SSH_KEY="${{MIGRATION_SSH_KEY:-{args.ssh_key}}}"\n'
        f'MIGRATION_RKE2_IMPORT_IMAGES="${{MIGRATION_RKE2_IMPORT_IMAGES:-{str(args.rke2_import_images).lower()}}}"\n'
        f'MIGRATION_REGISTRY="${{MIGRATION_REGISTRY:-{args.registry}}}"\n'
        f'MIGRATION_IMAGE_TAG="${{MIGRATION_IMAGE_TAG:-{args.image_tag}}}"\n'
        f'MIGRATION_DUMP_DIR="${{MIGRATION_DUMP_DIR:-{args.dump_dir}}}"\n'
        f'MIGRATION_DB_TARGETS="${{MIGRATION_DB_TARGETS:-{args.db_targets or ""}}}"\n'
        f'MIGRATION_ALLOW_SECRET_MATERIAL="${{MIGRATION_ALLOW_SECRET_MATERIAL:-{str(args.allow_secret_material).lower()}}}"\n'
        'ALLOW_FLAG=""\n'
        'if [ "$MIGRATION_ALLOW_SECRET_MATERIAL" = "true" ]; then ALLOW_FLAG="--allow-secret-material"; fi\n'
        'RKE2_IMPORT_FLAG="--rke2-import-images"\n'
        'if [ "$MIGRATION_RKE2_IMPORT_IMAGES" = "false" ]; then RKE2_IMPORT_FLAG="--no-rke2-import-images"; fi\n'
    )
    callback = (
        'python3 "$REPO_ROOT/scripts/migrate_project.py" '
        '--project-path "$PROJECT_PATH" --values "$VALUES" --namespace "$NAMESPACE" '
        '--output "$MIGRATION_OUTPUT" --private-dir "$MIGRATION_PRIVATE_DIR" --auto-prepare '
        '--image-mode "$MIGRATION_IMAGE_MODE" --image-output-dir "$MIGRATION_IMAGE_OUTPUT_DIR" '
        '--rke2-nodes "$MIGRATION_RKE2_NODES" --rke2-image-dir "$MIGRATION_RKE2_IMAGE_DIR" '
        '--ssh-user "$MIGRATION_SSH_USER" --ssh-key "$MIGRATION_SSH_KEY" '
        '$RKE2_IMPORT_FLAG '
        '--registry "$MIGRATION_REGISTRY" --image-tag "$MIGRATION_IMAGE_TAG" '
        '--dump-dir "$MIGRATION_DUMP_DIR" --db-targets "$MIGRATION_DB_TARGETS" '
        '--execute $ALLOW_FLAG '
    )
    write_file(
        output / "run-migration.sh",
        common
        + 'REPO_ROOT="${REPO_ROOT:-'
        + str(ROOT)
        + '}"\n'
        + f"{callback}--stage secrets\n"
        + f"{callback}--stage images\n"
        + f"{callback}--stage databases\n"
        + f"{callback}--stage manifests\n"
        + f"{callback}--stage validate\n",
        executable=True,
    )
    stage_scripts = {
        "01-sync-secrets.sh": "secrets",
        "02-build-and-push-images.sh": "images",
        "03-database-dump-restore.sh": "databases",
        "04-generate-routing-and-storage.sh": "manifests",
        "05-validate.sh": "validate",
    }
    for script_name, stage in stage_scripts.items():
        write_file(
            output / "scripts" / script_name,
            common
            + 'REPO_ROOT="${REPO_ROOT:-'
            + str(ROOT)
            + '}"\n'
            + f"{callback}--stage {stage}\n",
            executable=True,
        )

    db_target_example = {
        "databaseTargets": {
            "service-name-or-alias": {
                "host": "target-service-rw.namespace.svc",
                "port": 5432,
                "database": "target_db",
                "secretRef": {
                    "name": "target-service-app",
                    "namespace": "namespace",
                    "usernameKey": "username",
                    "passwordKey": "password",
                },
            }
        }
    }
    write_file(output / "db-targets.example.yaml", yaml.safe_dump(db_target_example, sort_keys=False))
    print(f"Migration automation bundle written to {output}")


def stage_secrets(args: argparse.Namespace, service_pairs: list[tuple[import_project.ServiceRecord, dict[str, Any]]]) -> None:
    secrets = []
    for record, service in service_pairs:
        entries = secret_entries(service)
        if entries:
            secrets.append((record, entries))
    print(f"Secret-bearing services: {len(secrets)}")
    if not args.execute:
        return
    if not args.allow_secret_material:
        raise SystemExit("Refusing to read/apply secret material without --allow-secret-material.")
    for record, entries in secrets:
        manifest = {
            "apiVersion": "v1",
            "kind": "Secret",
            "metadata": {
                "name": k8s_name(record.name, "import-env"),
                "namespace": args.namespace,
                "labels": {"app.kubernetes.io/managed-by": "urban-platform-import"},
            },
            "type": "Opaque",
            "stringData": entries,
        }
        run_command(["kubectl", "-n", args.namespace, "apply", "-f", "-"], stdin=yaml.safe_dump(manifest, sort_keys=False))


def stage_images(args: argparse.Namespace, project_path: Path, service_pairs: list[tuple[import_project.ServiceRecord, dict[str, Any]]]) -> None:
    candidates = []
    for record, service in service_pairs:
        if record.kind != "application" and not record.build_only:
            continue
        image = record.image
        build = service.get("build")
        needs_tag = record.build_only or (image is not None and (not image.tag or image.tag in import_project.MUTABLE_TAGS))
        if needs_tag:
            candidates.append((record, service, build))
    print(f"Application image promotion candidates: {len(candidates)}")
    if not args.execute:
        return
    if args.image_mode == "skip":
        print("Image migration skipped by MIGRATION_IMAGE_MODE=skip. Keep these services on Compose or provide images another way.")
        return
    if args.image_mode == "registry" and not args.registry:
        raise SystemExit("Refusing image promotion without --registry or MIGRATION_REGISTRY.")
    ensure_registry_login(args)
    archive_dir = Path(args.image_output_dir).expanduser()
    if args.image_mode == "preload":
        archive_dir.mkdir(parents=True, exist_ok=True)
    skipped: list[str] = []
    failed: list[str] = []
    for record, service, build in candidates:
        target_image = local_import_image(args, record)
        compose_path = relative_compose_file(project_path, record.file)
        try:
            if build:
                if isinstance(build, dict):
                    context = compose_path.parent / str(build.get("context", "."))
                    dockerfile = str(build.get("dockerfile", "Dockerfile"))
                else:
                    context = compose_path.parent / str(build)
                    dockerfile = "Dockerfile"
                run_command(["docker", "build", "-t", target_image, "-f", dockerfile, "."], cwd=context.resolve())
            elif record.image:
                if not ensure_source_image(record):
                    skipped.append(f"{record.file}::{record.name} ({record.image.display})")
                    continue
                run_command(["docker", "tag", record.image.display, target_image])
            if args.image_mode == "registry":
                run_command(["docker", "push", target_image])
            elif args.image_mode == "preload":
                run_command(["docker", "save", "-o", str(archive_dir / image_archive_name(record)), target_image])
        except subprocess.CalledProcessError as exc:
            failed.append(f"{record.file}::{record.name} ({exc.cmd})")
    if args.image_mode == "preload":
        preload_archives_to_nodes(args, archive_dir)
    if skipped:
        print("Skipped image candidates:")
        for item in skipped:
            print(f"- {item}")
    if failed:
        print("Failed image candidates:")
        for item in failed:
            print(f"- {item}")
        raise SystemExit(f"Image migration completed with {len(failed)} failed candidate(s).")


def stage_databases(args: argparse.Namespace, service_pairs: list[tuple[import_project.ServiceRecord, dict[str, Any]]]) -> None:
    db_targets_path = args.db_targets or str(Path(args.private_dir).expanduser() / "db-targets.yaml")
    targets = read_database_targets(db_targets_path)
    dump_dir = Path(args.dump_dir).expanduser()
    candidates = [
        (record, service)
        for record, service in service_pairs
        if record.kind in {"postgresql", "postgis", "timescaledb"}
    ]
    print(f"PostgreSQL-family migration candidates: {len(candidates)}")
    if not args.execute:
        return
    if not args.allow_secret_material:
        raise SystemExit("Refusing database dump/restore without --allow-secret-material.")
    dump_dir.mkdir(parents=True, exist_ok=True)
    for record, service in candidates:
        port = published_port(record)
        env = postgres_env(service)
        if not port or not env["password"]:
            print(f"Skipping {record.file}::{record.name}: missing published port or POSTGRES_PASSWORD.")
            continue
        alias = k8s_name(record.name)
        dump_file = dump_dir / f"{alias}.dump"
        run_env = os.environ.copy()
        run_env["PGPASSWORD"] = env["password"]
        run_command(
            [
                "pg_dump",
                "--format=custom",
                "--no-owner",
                "--no-acl",
                "--host",
                "127.0.0.1",
                "--port",
                port,
                "--username",
                env["user"],
                "--dbname",
                env["database"],
                "--file",
                str(dump_file),
            ],
            env=run_env,
        )
        target_dsn = target_dsn_from_mapping(targets.get(record.name) or targets.get(alias), args.namespace)
        if target_dsn:
            restore_env = os.environ.copy()
            run_command(
                [
                    "pg_restore",
                    "--clean",
                    "--if-exists",
                    "--no-owner",
                    "--dbname",
                    target_dsn,
                    str(dump_file),
                ],
                env=restore_env,
            )
        else:
            print(f"Dumped {alias}; no usable target mapping found in {db_targets_path}, so restore was skipped.")


def stage_manifests(args: argparse.Namespace, service_pairs: list[tuple[import_project.ServiceRecord, dict[str, Any]]]) -> None:
    output = Path(args.output).expanduser()
    manifests: list[dict[str, Any]] = []
    for record, service in service_pairs:
        if record.kind == "nginx" and import_project.has_edge_publish(record.ports):
            name = k8s_name(record.name)
            manifests.append(
                {
                    "apiVersion": "networking.k8s.io/v1",
                    "kind": "Ingress",
                    "metadata": {
                        "name": f"{name}-traefik",
                        "namespace": args.namespace,
                        "annotations": {"traefik.ingress.kubernetes.io/router.entrypoints": "websecure"},
                    },
                    "spec": {
                        "ingressClassName": "traefik",
                        "rules": [
                            {
                                "http": {
                                    "paths": [
                                        {
                                            "path": "/",
                                            "pathType": "Prefix",
                                            "backend": {
                                                "service": {"name": name, "port": {"number": 80}}
                                            },
                                        }
                                    ]
                                }
                            }
                        ],
                    },
                }
            )
    content = GENERATED_HEADER + yaml.safe_dump_all(manifests, sort_keys=False)
    path = output / "manifests" / "traefik-ingress-candidates.yaml"
    write_file(path, content)
    print(f"Wrote {path}")
    if args.execute and manifests:
        run_command(["kubectl", "-n", args.namespace, "apply", "-f", str(path)])


def stage_validate(args: argparse.Namespace) -> None:
    command = [
        "python3",
        str(ROOT / "scripts/import_project.py"),
        "--project-path",
        args.project_path,
        "--values",
        args.values,
        "--ingress-controller",
        args.ingress_controller,
        "--webserver",
        args.webserver,
        "--database",
        args.database,
        "--report",
        str(Path(args.output).expanduser() / "post-migration-check.md"),
    ]
    if args.redact_sensitive:
        command.append("--redact-sensitive")
    if args.execute:
        run_command(command)
    else:
        print("Validation command:")
        print(" ".join(command))


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate or execute guarded project migration automation.")
    parser.add_argument("--project-path", required=True)
    parser.add_argument("--values", default=str(DEFAULT_VALUES))
    parser.add_argument("--image-policy", default=str(import_project.DEFAULT_IMAGE_POLICY))
    parser.add_argument("--output", default="reports/import-migration")
    parser.add_argument("--namespace", default="urban-platform")
    parser.add_argument("--ingress-controller", choices=["traefik", "nginx"], default="traefik")
    parser.add_argument("--webserver", choices=["nginx", "apache-httpd", "apache-tomcat", "traefik"], default="nginx")
    parser.add_argument("--database", default="postgresql")
    parser.add_argument("--image-mode", choices=["registry", "preload", "skip"], default="registry")
    parser.add_argument("--image-output-dir", default="/var/lib/urban-platform/private/images")
    parser.add_argument("--rke2-nodes", default="")
    parser.add_argument("--rke2-image-dir", default="/var/lib/rancher/rke2/agent/images")
    parser.add_argument("--ssh-user", default="root")
    parser.add_argument("--ssh-key", default="")
    parser.add_argument("--rke2-import-images", dest="rke2_import_images", action="store_true", default=True)
    parser.add_argument("--no-rke2-import-images", dest="rke2_import_images", action="store_false")
    parser.add_argument("--registry", default="")
    parser.add_argument("--image-tag", default="imported-0.1.0")
    parser.add_argument("--private-dir", default=str(DEFAULT_PRIVATE_DIR))
    parser.add_argument("--dump-dir", default="/var/lib/urban-platform/private/db-dumps")
    parser.add_argument("--db-targets", default="")
    parser.add_argument("--stage", choices=["prepare", "bundle", "secrets", "images", "databases", "manifests", "validate", "all"], default="bundle")
    parser.add_argument("--auto-prepare", action="store_true")
    parser.add_argument("--execute", action="store_true")
    parser.add_argument("--allow-secret-material", action="store_true")
    parser.add_argument("--redact-sensitive", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    project_path, compose_files, service_pairs, findings, values = load_context(args)
    if args.auto_prepare and args.stage != "prepare":
        stage_prepare(args, project_path, compose_files, service_pairs, findings, values)
    if args.stage == "prepare":
        stage_prepare(args, project_path, compose_files, service_pairs, findings, values)
    if args.stage in {"bundle", "all"}:
        generate_bundle(args, project_path, service_pairs, findings, values)
        print_bundle_files(Path(args.output).expanduser())
        if args.stage == "bundle" and args.execute:
            print("Execute mode was set, but stage `bundle` only writes automation files. Use --stage all or a specific --stage to run actions.")
    if args.stage in {"secrets", "all"}:
        stage_secrets(args, service_pairs)
    if args.stage in {"images", "all"}:
        stage_images(args, project_path, service_pairs)
    if args.stage in {"databases", "all"}:
        stage_databases(args, service_pairs)
    if args.stage in {"manifests", "all"}:
        stage_manifests(args, service_pairs)
    if args.stage in {"validate", "all"}:
        stage_validate(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
